// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Chey Rasmussen
// foil/provenance.ts — sidecar v4: honest mask provenance + the AI learning loop.
//
// Chey, 2026-08-07: "We'll want to mark when masks are generated by an AI as
// well, because once i've made a few hand-done masks, i want an AI to be able
// to learn from mine to be able to do its best at replicating it across other
// cards in similar sets/series - and then i want to be able to correct the
// agents' mask such that it can then observe the diff and continue to improve
// without me having to hand-paint all the masks."
//
// So provenance here is not a label — it is the record that makes that loop
// mechanical:
//
//   1. WHAT MADE ME        derivation_method + prior.source (+ prior.generator)
//   2. FROM WHAT           prior.generator.exemplars (the human masks it learned
//                          from) / correction.parent (the mask a human edited)
//   3. WHAT THE HUMAN      correction.{parentPng, parentDiffPng, metrics, grid}
//      CHANGED AFTERWARDS  — the training signal, kept as pixels AND numbers
//
// THE LABEL IS NEVER TRUSTED FROM THE CLIENT. `deriveMethod()` decides it by
// diffing the saved pixels against the pixels the claimed starting point
// actually produces. A caller can only *claim* a machine label by supplying a
// full generator identity (name/version/runId/exemplars) — see writeMaskRecord.
//
// v5 (#10, 2026-09-06) adds two RECORDED fields — `author` and `verification` —
// and one DERIVED one, `provenanceTier`. They exist because EXEMPLAR_WEIGHT was
// calibrated when the only hand in the corpus was the owner's, so `hand` meant
// both "a human painted this" and "this is correct". With outside contributors
// those are two different claims, and only the first one is visible in the
// pixels. So exemplar weight now follows VERIFICATION rather than authorship:
// a contributor's mask is recorded honestly, merged if it is good, and carries
// weight 0 for rule derivation until a writer says otherwise. See
// docs/PROVENANCE.md § "Provenance tiers".
//
// v4 (4b, 2026-09-01) adds one field, `frame`, and it obeys the same rule as
// the label: DERIVED, NEVER CLAIMED. Masks now live in CANONICAL SPACE — the
// physical card, 63 x 88 mm at 8 px/mm = 504 x 704 — instead of the 490 x 674
// raster that was 2x TCGdex's 245:337 and 1.55% short of a real card. A mask is
// a stencil, and a stencil only fits if the picture underneath is the shape it
// was cut for, so the stencil is cut to the CARD and every image source
// declares its own transform into that space (data/frames.json). `frame` is
// re-inferred on every read — and inferred from THE MASK PNG'S OWN HEADER
// wherever the file is in reach, not from the width/height the JSON declares,
// because a number in the JSON is a claim and the pixels are not. A
// hand-edited sidecar cannot claim a framing its own pixels deny.
// v1/v2/v3 compatibility is permanent.
//
// See docs/MASK-PIPELINE.md § "Sidecar v3" for the schema.

import { createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { open, readFile, writeFile, unlink, rm, readdir } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import {
  decodePng,
  encodePng,
  diffMask,
  rasterizePriorAlpha,
  renderPriorPng,
  type DiffStats,
  type MaskPrior,
} from './mask-artifacts.ts';
import type { RgbaImage } from './png.ts';
import { headerDims, HEADER_BYTES } from './image-dims.ts';
import { assertAuthorable, resolveFrame, UNKNOWN_FRAME_ID } from './frames.ts';
import { isWriter } from '@foilkit/core';

export const SIDECAR_VERSION = 5;

/**
 * The first sidecar generation that is expected to CARRY provenance identity.
 *
 * Below it, absence is historical fact rather than a gap — see `deriveTier`.
 */
export const FIRST_ATTRIBUTED_VERSION = 5;

/** alpha >= 128 counts as foil (same threshold as diffMask). */
const FOIL_THRESHOLD = 128;

// ── The taxonomy ───────────────────────────────────────────────────────────
//
// Five values, covering the four cases that must stay distinguishable:
// pure machine geometry / pure human / human-corrected-machine / machine-unreviewed.

export type DerivationMethod =
  /** Machine geometry only: a window/era rect baked to pixels, not a stroke painted on it. */
  | 'layout-flatten'
  /** Human-painted from scratch or straight from a layout/window prior. */
  | 'hand'
  /** Human-painted ON TOP of an existing NON-AI mask (a bake, or an earlier hand mask). */
  | 'hand-refined'
  /** Machine-generated by a mask generator, NOT yet looked at by a human. */
  | 'ai'
  /** An AI-derived mask a human then edited — the correction record is the product. */
  | 'ai-corrected';

export const DERIVATION_METHODS: readonly DerivationMethod[] = [
  'layout-flatten',
  'hand',
  'hand-refined',
  'ai',
  'ai-corrected',
];

/** Who actually put the pixels there. */
export type Authorship = 'human' | 'machine' | 'mixed';

/** Has a human looked at this mask? Drives the "unreviewed" badge + the queue. */
export type ReviewStatus =
  /** A human painted these pixels. */
  | 'human-authored'
  /** A human chose the geometry (window handles) but painted nothing. */
  | 'human-adjusted'
  /** Machine output no human has touched. NEVER an exemplar. */
  | 'unreviewed';

export const AUTHORSHIP_BY_METHOD: Record<DerivationMethod, Authorship> = {
  'layout-flatten': 'machine',
  hand: 'human',
  'hand-refined': 'human',
  ai: 'machine',
  'ai-corrected': 'mixed',
};

export const REVIEW_BY_METHOD: Record<DerivationMethod, ReviewStatus> = {
  'layout-flatten': 'human-adjusted',
  hand: 'human-authored',
  'hand-refined': 'human-authored',
  ai: 'unreviewed',
  'ai-corrected': 'human-authored',
};

/**
 * ANTI-FEEDBACK-COLLAPSE (the safeguard, enforced in code — not a convention).
 *
 * A generator that learns from its own unreviewed output converges on its own
 * mistakes. So exemplar eligibility is a property of WHO PAINTED THE PIXELS:
 *
 *   - `hand` / `hand-refined` — a human painted them. Ground truth, weight 1.
 *   - `ai-corrected`          — a human painted ON an AI mask. Real signal, but
 *                               anchored by what the AI proposed, so it is
 *                               deliberately worth LESS than an unanchored
 *                               human mask (weight 0.6).
 *   - `ai`                    — unreviewed machine output. Weight 0: it can
 *                               never be an exemplar, at any corpus size.
 *   - `layout-flatten`        — a rect the machine rasterized; teaches only the
 *                               rect the generator already knows. Weight 0.
 *
 * `selectExemplars()` is the ONLY sanctioned way to pick training masks; the
 * codify ritual and every generator go through it.
 */
export const EXEMPLAR_WEIGHT: Record<DerivationMethod, number> = {
  'layout-flatten': 0,
  hand: 1,
  'hand-refined': 1,
  ai: 0,
  'ai-corrected': 0.6,
};

// ── Provenance tiers (#10): weight follows VERIFICATION, not authorship ────
//
// EXEMPLAR_WEIGHT above answers "what kind of hand made these pixels". That was
// the whole question while the only hand was the owner's, because `hand` then
// meant both "a human painted this" and "this is how the card truly is". The
// contribution pipeline separates those: a stranger's mask is unmistakably
// human-painted and says nothing at all about whether it is right.
//
// So there is a second axis, and it is NOT "who": it is "has somebody with the
// writer capability looked". A merged contribution is ACCEPTED — it is good
// enough to live in the corpus, be served, be rendered, be built on — and that
// is a lower bar than EXEMPLAR-GRADE, which means "a generator may derive the
// rule for a whole era from this". Merge is the first; verification is the
// second; conflating them is how one unreviewed mask silently rewrites a
// region policy.

export type ProvenanceTier =
  /** A writer-capability holder authored these pixels, or has verified them. */
  | 'owner-verified'
  /** A named human who is not a writer authored them. Nobody has verified. */
  | 'contributor'
  /** No human attribution: machine output, or a v5+ record with no `author`. */
  | 'unattributed';

export const PROVENANCE_TIERS: readonly ProvenanceTier[] = ['owner-verified', 'contributor', 'unattributed'];

/** Which tiers count as verified for weight purposes. Exactly one does. */
export const TIER_IS_VERIFIED: Record<ProvenanceTier, boolean> = {
  'owner-verified': true,
  contributor: false,
  unattributed: false,
};

/**
 * THE WEIGHT TABLE, keyed by (derivation_method × verification tier).
 *
 * The `owner-verified` row IS the historical `EXEMPLAR_WEIGHT` table, unchanged
 * — every number calibrated before contributors existed still describes exactly
 * the situation it was calibrated for, which is the owner's own work.
 *
 * The other two rows are ZERO ACROSS THE BOARD, and that is a choice rather
 * than an oversight. The spec allowed "low or zero"; here is why low is worse:
 *
 *   * `region-learn.learnPolicy` takes a WEIGHTED MEAN of per-class foil share
 *     over a pool that is single-digit today, then crosses a hard threshold at
 *     `voteThreshold` 0.5. With Σweight ≈ 2–3, even w = 0.1 moves a class share
 *     by several points — enough to flip `carriesFoil` at the margin. "Low" is
 *     not "harmless"; it is "changes the answer, quietly, with nobody having
 *     looked".
 *   * Any weight above zero ADMITS the mask to the pool at all, because
 *     `isExemplarEligible` is a `> 0` gate. Admitted means: it becomes a
 *     `PolicyExemplar`, it is cited by `ExemplarRef` on every mask generated
 *     from that pool, it counts toward `exemplarsInGroup`, and it lowers
 *     `leverage = printings ÷ (exemplars + 1)` — the number that decides where
 *     the maintainer spends the next hour. A contribution nobody has reviewed
 *     must not be able to make a rule group look SERVED.
 *   * Zero is reversible in one owner action, and the full weight comes back
 *     (`writeVerification`). A nonzero default is not reversible in any useful
 *     sense: by the time anyone notices, it has already moved every derived
 *     number downstream.
 *
 * 3a measured that most current evidence is `ai-corrected` at 0.6 rather than
 * `hand` at 1 — the pool is already thin and already discounted. Thin is a
 * reason to be MORE careful about what joins it, not less.
 */
export const EXEMPLAR_WEIGHT_BY_TIER: Record<ProvenanceTier, Record<DerivationMethod, number>> = {
  'owner-verified': { ...EXEMPLAR_WEIGHT },
  contributor: { 'layout-flatten': 0, hand: 0, 'hand-refined': 0, ai: 0, 'ai-corrected': 0 },
  unattributed: { 'layout-flatten': 0, hand: 0, 'hand-refined': 0, ai: 0, 'ai-corrected': 0 },
};

/**
 * The weight this (method, tier) pair carries as training input.
 *
 * `tier` defaults to `owner-verified`, which makes the one-argument call read
 * as THE CEILING for a method — "what is a `hand` mask worth at best" — which
 * is the pre-#10 question and still has the pre-#10 answer. That default is
 * safe here because the caller is naming a method in the abstract. It would NOT
 * be safe when the caller holds a record; see `exemplarWeightOf`.
 */
export function exemplarWeightFor(method: DerivationMethod, tier: ProvenanceTier = 'owner-verified'): number {
  return EXEMPLAR_WEIGHT_BY_TIER[tier][method];
}

export function isExemplarEligible(method: DerivationMethod, tier: ProvenanceTier = 'owner-verified'): boolean {
  return exemplarWeightFor(method, tier) > 0;
}

/**
 * The weight a SPECIFIC RECORD carries. THE function selection uses.
 *
 * FAILS CLOSED, and does not reuse the default above. A record whose
 * `provenanceTier` is missing or unrecognised is worth 0 — not "worth whatever
 * the method would be worth at best", which is what falling through to
 * `exemplarWeightFor`'s default would silently do. That distinction is the
 * whole subtask in one line: the dangerous failure is a record of unknown
 * standing being treated as ground truth, and it is dangerous in exactly the
 * place a helpful default is most tempting. Every real read path fills the
 * field (`normalizeSidecar` derives it on every load), so an absent one means
 * the value did not come from a read path.
 */
export function exemplarWeightOf(s: Pick<MaskSidecar, 'derivation_method' | 'provenanceTier'>): number {
  const row = EXEMPLAR_WEIGHT_BY_TIER[s.provenanceTier] as Record<DerivationMethod, number> | undefined;
  return row?.[s.derivation_method] ?? 0;
}

// ── Authorship and verification, as RECORDS ────────────────────────────────
//
// Two fields with opposite trust models, and the split is the whole design:
//
//   `author`        RECORDED. The server writes it from the identity it already
//                   verified — a signed session cookie on the direct-write
//                   path, the same on the contribution path, where the App
//                   composes the commit and the contributor never touches the
//                   bytes. A client cannot supply it; `functions/_lib/validate.ts`
//                   REFUSES a submission that carries one at all.
//
//   `verification`  DERIVED-OR-OWNER-ASSERTED, and only honoured when the
//                   system can check it. `deriveTier` believes a verification
//                   block only when `verifiedBy` holds the writer capability
//                   (`@foilkit/core`'s WRITERS — the same list the write route
//                   enforces). A stranger who hand-commits
//                   `verification: { verifiedBy: 'themselves' }` in a fork PR
//                   gets `contributor` back and weight 0.
//
// THE RESIDUAL HOLE, stated rather than papered over — and it is THREE DOORS
// to the same room, not one. A hand-crafted pull request (never the App; a
// human reads such a diff before merging) can reach owner-verified weight by:
//
//   1. `verification: { verifiedBy: 'cheyras', via: 'writer-direct' }` over
//      pixels no writer ever saw — the loud one; the name is in the diff.
//   2. `author: { login: 'cheyras', id: null, via: 'local-cli' }` with no
//      verification block at all — byte-identical to `HISTORICAL_AUTHOR`, so
//      the reader cannot tell it from a legitimate pre-contributor record.
//   3. `"version": 3` with `author` omitted — the quiet one: the historical
//      inference then stamps owner-verified, and the lie is a single digit a
//      reviewer has been trained to read as legacy compat.
//
// Nothing in the file can disprove any of the three, because the repository
// has no signature over sidecar bytes. What closes them is the same fact each
// time: none can come from the App (both write paths compose sidecars
// server-side and hardcode `version`), so each requires a fork PR whose diff a
// human reads — and a reviewer of ANY sidecar diff should treat `version`,
// `author`, and `verification` as claims the diff itself cannot prove.
// `deriveTier`'s tests pin all three doors as known and accepted.

/** How the server learned who authored these pixels. */
export type AuthorChannel =
  /** The writer-gated direct write (`functions/mask.ts` PUT). */
  | 'writer-direct'
  /** The contribution pipeline (`functions/contribute.ts`), App-composed. */
  | 'contribution-pr'
  /** A generator run. No human author; `login` is the generator's name. */
  | 'generator'
  /** A local CLI write by whoever holds the checkout. */
  | 'local-cli';

export interface AuthorIdentity {
  /** GitHub login, as the verified session reported it. */
  login: string;
  /** GitHub's numeric user id — stable across a rename. Null for a generator. */
  id: number | null;
  /** WHICH ROUTE recorded this. Never taken from a request body. */
  via: AuthorChannel;
}

/**
 * A writer's "I have looked at this, and it is exemplar-grade".
 *
 * Written ONLY by `writeVerification`, which the writer-gated routes call after
 * they have re-derived the login from a signed cookie. `note` is the owner's
 * own words about why.
 */
export interface VerificationRecord {
  /** The verifier's GitHub login. Honoured only if it holds the capability. */
  verifiedBy: string;
  verifiedById: number | null;
  verifiedAt: string;
  /** The route that produced it. Only writer-gated routes may write one. */
  via: 'writer-direct' | 'local-cli';
  note: string | null;
}

/**
 * THE TIER, decided rather than read.
 *
 * Recomputed on every `normalizeSidecar`, exactly like `authorship`,
 * `reviewStatus` and `frame`, so a hand-edited `provenanceTier` field is
 * ignored. The ladder, in order:
 *
 *   1. A verification block whose `verifiedBy` holds the writer capability, on
 *      a route that may write one ⇒ `owner-verified`. This is the PROMOTION.
 *   2. No verification, but `author` is a writer who wrote through a
 *      writer-gated route ⇒ `owner-verified` BY CONSTRUCTION. The direct-write
 *      path runs as the capability holder; asking him to then verify his own
 *      save would be a ritual, not a check.
 *   3. `author` present, anyone else ⇒ `contributor`. A merged contribution is
 *      accepted, not exemplar-grade.
 *   4. No `author` at all, on a record older than v5 ⇒ `owner-verified`. That
 *      is HISTORICAL TRUTH and not a guess: every mask in this corpus predates
 *      the contribution pipeline, and the sole-author fact is recorded in
 *      RELICENSE.md. v1–v4 compatibility is permanent, and it has to include
 *      the tier or the whole existing corpus would silently drop to weight 0.
 *   5. No `author`, on a v5-or-later record ⇒ `unattributed`, which is weight
 *      0. Conservative on purpose and in exactly the direction the historical
 *      rule is generous: from v5 on, every write path stamps an author, so an
 *      absent one means the record was assembled by something that is not one
 *      of them, and the safe reading of "I do not know who made this" is not
 *      "the owner did".
 */
/**
 * The author every pre-v5 record has, stated once.
 *
 * Not a default and not a guess: RELICENSE.md records that every byte of this
 * corpus was authored by one person, and every one of those masks predates the
 * contribution pipeline by construction — the pipeline is what created the
 * possibility of a second author. `provenance.test.ts` asserts this login still
 * holds the writer capability, so the constant and the list cannot drift into
 * disagreement in silence.
 */
export const HISTORICAL_AUTHOR: AuthorIdentity = { login: 'cheyras', id: null, via: 'local-cli' };

/**
 * WHO a record is attributable to, recorded value first and history second.
 *
 * A pre-v5 record names no author, and the honest reading of that absence
 * depends on what else the record says:
 *
 *   * IT DESCENDS FROM A GENERATOR and no human has painted over it
 *     (`derivation_method: 'ai'`) — then the author is the generator, and the
 *     tier is `unattributed`. Reading those as the owner's work would put a
 *     green "owner-verified" beside the amber "AI · UNREVIEWED" badge on the
 *     same mask, which is a contradiction the corpus should never display.
 *     They are weight 0 either way, so nothing downstream moves; what moves is
 *     whether the record TELLS THE TRUTH about itself.
 *   * ANYTHING ELSE — a human painted it, and there was exactly one human.
 *     RELICENSE.md records that; the contribution pipeline is what created the
 *     possibility of a second author, and every one of these predates it.
 *
 * `ai-corrected` and `layout-flatten` fall in the second branch deliberately:
 * a correction is the owner's own brushwork over a proposal, and a bake is a
 * rect he chose. Both were his acts even though a machine made the pixels
 * underneath.
 */
export function effectiveAuthor(
  s: Pick<MaskSidecar, 'version' | 'author' | 'derivation_method'> & { prior?: { generator?: { name: string } | null } },
): AuthorIdentity | null {
  if (s.author) return s.author;
  if (s.version >= FIRST_ATTRIBUTED_VERSION) return null;
  const gen = s.prior?.generator;
  if (gen && s.derivation_method === 'ai') return { login: gen.name, id: null, via: 'generator' };
  return HISTORICAL_AUTHOR;
}

/**
 * The author to stamp when a record's VERSION is about to be bumped to v5.
 *
 * This exists because the historical inference is keyed on the version, and a
 * schema upgrade changes the version. Without it, the first `corpus.ts migrate`
 * (or frame migration) after #10 would rewrite the entire committed corpus as
 * v5-with-no-author — which reads back as `unattributed`, weight 0, and would
 * empty the exemplar pool that every rule in this project is derived from. The
 * upgrade has to MATERIALISE what the old version implied, not merely renumber
 * the file and let the implication expire.
 *
 * Same function as `effectiveAuthor`, named separately because the two uses
 * differ in kind and one of them writes to disk: reading an old record infers,
 * upgrading it RECORDS the inference. The name is what tells a reader which
 * just happened.
 */
export const authorForUpgrade = effectiveAuthor;

/**
 * The SCHEMA UPGRADE, as a pure function over the raw JSON.
 *
 * Extracted out of `corpus.ts migrate` when the v4→v5 pass found the bug this
 * function's last clause exists to prevent: the CLI synthesized a fresh
 * single-entry `lineage` unconditionally, which was harmless for as long as the
 * command only ever met pre-v3 records (they have no lineage), and which
 * silently deleted the entire 4b frame-migration history the first time it met
 * a v4 one. A migration that loses history is worse than no migration, and a
 * migration that lives only inside a CLI is a migration nothing can test.
 *
 * WHAT IT WRITES, and why each one:
 *
 *   * every DERIVED field from `norm` — the label, the rollups, the frame, the
 *     tier — because the point of an upgrade is to record what the current
 *     rules say, not to renumber a file and leave stale claims in it;
 *   * the AUTHOR, materialised via `effectiveAuthor`, because the historical
 *     inference is keyed on the version and this is the version bump;
 *   * the existing `lineage`, untouched, whenever there is one.
 *
 * Everything else in `raw` is spread through unchanged. It never touches the
 * mask PNG and never re-labels: from v3 on the label is computed from pixels at
 * write time, and a pre-v3 `derivation_method: 'hand'` was a placeholder that
 * happens to be true (see the module header).
 */
export function upgradeSidecarRecord(raw: Record<string, unknown>, norm: MaskSidecar): Record<string, unknown> {
  const author = effectiveAuthor(norm);
  return {
    ...raw,
    version: SIDECAR_VERSION,
    artworkKey: norm.artworkKey,
    // Written from the INFERRED value, never from whatever the file claimed.
    frame: norm.frame,
    derivation_method: norm.derivation_method,
    authorship: norm.authorship,
    reviewStatus: norm.reviewStatus,
    ...(author ? { author } : {}),
    ...(norm.verification ? { verification: norm.verification } : {}),
    provenanceTier: norm.provenanceTier,
    artworkUrl: norm.artworkUrl,
    lineage: Array.isArray(raw.lineage)
      ? raw.lineage
      : [
          {
            method: norm.derivation_method,
            savedAt: norm.savedAt ?? null,
            source: norm.prior?.source ?? 'layout',
            generator: null,
          },
        ],
  };
}

export function deriveTier(
  version: number,
  author: AuthorIdentity | null | undefined,
  verification: VerificationRecord | null | undefined,
): ProvenanceTier {
  if (
    verification &&
    (verification.via === 'writer-direct' || verification.via === 'local-cli') &&
    isWriter(verification.verifiedBy)
  ) {
    return 'owner-verified';
  }
  if (author && typeof author.login === 'string') {
    // A generator is not a person. `login` there is a generator NAME, and
    // reading it as a contributor login would put machine output one owner
    // click away from full weight. It is `unattributed` — which is also what
    // the method already says (`ai` is weight 0 in every tier).
    if (author.via === 'generator') return 'unattributed';
    const gated = author.via === 'writer-direct' || author.via === 'local-cli';
    return gated && isWriter(author.login) ? 'owner-verified' : 'contributor';
  }
  return version < FIRST_ATTRIBUTED_VERSION ? 'owner-verified' : 'unattributed';
}

// ── Generator identity (the "what made me" half of the chain) ───────────────

/** One human mask a generator learned from. */
export interface ExemplarRef {
  cardId: string;
  variantId: number;
  /** The exemplar's own savedAt — pins WHICH version was learned from. */
  savedAt: string | null;
  /** The exemplar's method at selection time (always human-authored — see EXEMPLAR_WEIGHT). */
  method: DerivationMethod;
  /**
   * The exemplar's provenance tier at selection time. Always `owner-verified`
   * today — selection admits nothing else — but recorded rather than assumed,
   * so a citation stays readable if the table ever admits a second tier.
   */
  tier?: ProvenanceTier;
  /** Weight this exemplar carried in the run. */
  weight: number;
}

/**
 * Who/what generated a machine mask. Recorded verbatim on the mask AND carried
 * forward onto every human correction of it, so a correction can always answer
 * "which generator, which run, which exemplars produced the thing I fixed".
 */
export interface GeneratorIdentity {
  /** Stable generator name, e.g. 'window-artgate'. */
  name: string;
  /** Generator version — bump when its behavior changes meaning. */
  version: number;
  /** Model id when a model was involved; null for classical-CV generators. */
  modelId: string | null;
  /** Unique id for the batch this mask came out of (groups a trial batch). */
  runId: string;
  /** Everything needed to reproduce the run. */
  params: Record<string, number | string | boolean>;
  /** The human masks it learned from. Empty = it learned from nothing (say so). */
  exemplars: ExemplarRef[];
  /** Generator's own confidence in THIS mask, 0..1, or null if it emits none. */
  confidence: number | null;
  generatedAt: string;
}

// ── Correction record (the training signal) ────────────────────────────────

/** Where the human's corrections landed, as a coarse grid of change fractions. */
export interface CorrectionGrid {
  /** Grid is size × size cells, row-major from the TOP-LEFT of the mask. */
  size: number;
  /** Fraction of each cell's pixels the human changed, 0..1, 3 dp. */
  cells: number[];
}

export interface CorrectionRecord {
  /** The mask the human edited. Its pixels are kept at `parentPng`. */
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    /** sha256 of the parent PNG bytes — pins the exact pixels corrected. */
    sha256: string;
    /** Carried forward when the parent was machine-made. */
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the parent mask's pixels. */
  parentPng: string;
  /** Filename of the human-vs-parent diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** Pixels the human ADDED to the parent. */
  addedPx: number;
  /** Pixels the human REMOVED from the parent. */
  removedPx: number;
  /** Foil pixels human and parent agree on. */
  unchangedPx: number;
  /** Jaccard(human, parent) — 1.0 = the parent was already right. */
  agreement: number;
  /** addedPx + removedPx. */
  changedPx: number;
  /** changedPx / (width*height) — how much of the face the human touched. */
  changedFraction: number;
  /** Bounding box of the changed pixels, UV y-up [x,y,w,h]; null when nothing changed. */
  bbox: [number, number, number, number] | null;
  /** Where the corrections concentrate. */
  grid: CorrectionGrid;
}

// ── Supersede record (a machine write that REPLACED a real mask) ───────────
//
// Distinct from `correction` on purpose. `correction` means "a human edited
// what was here" and is training signal. This means "a generator replaced what
// was here, and no human has agreed yet" — the opposite direction. Blurring
// them would feed a generator's own reshaping back as if a human had endorsed
// it, which is exactly what EXEMPLAR_WEIGHT exists to prevent.
//
// The replaced mask survives twice over: `.parent.png` holds its pixels for
// review, and `archiveDir` holds a VERBATIM copy of every artifact it had, so
// `restoreSuperseded()` puts the original back byte-for-byte — sha256-verified.
// A proposal you cannot un-propose is not a proposal.

export interface SupersededRecord {
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    sha256: string;
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the replaced mask's pixels. */
  parentPng: string;
  /** Filename of the machine-vs-replaced diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** The generator run that did it — the handle `revert --run-id` uses. */
  runId: string;
  /** Directory (relative to the mask's own dir) of the verbatim archive. */
  archiveDir: string;
  /** basename → sha256 of the archived bytes. Restore verifies every one. */
  archive: Record<string, string>;
  addedPx: number;
  removedPx: number;
  unchangedPx: number;
  agreement: number;
  changedPx: number;
  changedFraction: number;
  bbox: [number, number, number, number] | null;
  grid: CorrectionGrid;
}

// ── The sidecar ────────────────────────────────────────────────────────────

/** Card context, so a generator lane can group by set/series with no DB. */
export interface MaskCardContext {
  setId: string | null;
  seriesSlug: string | null;
  name: string | null;
  number: string | null;
}

/** One compact ancestry entry (pixels are NOT kept beyond the direct parent). */
export interface LineageEntry {
  method: DerivationMethod;
  /**
   * WHEN THE HUMAN SAVED, carried forward verbatim. On a frame-migration entry
   * this is the pre-migration save's timestamp and is deliberately NOT
   * re-stamped — the alias rule picks the newest save per (cardId, scope) and
   * re-stamping would misreport when the work happened. It therefore does NOT
   * date the migration; `migratedAt` does.
   */
  savedAt: string | null;
  source: MaskPrior['source'];
  generator: { name: string; version: number; runId: string } | null;
  /**
   * v4 (4b): set on a FRAME MIGRATION entry — the mask's pixels were resampled
   * from one frame into another. `derivation_method` deliberately does NOT move
   * with it: nobody repainted anything, so a `hand` mask stays `hand`.
   */
  frameMigration?: { from: string; to: string; runId: string };
  /**
   * WHEN THE MIGRATION RAN. Present exactly on entries that carry
   * `frameMigration`, and it exists because `savedAt` above answers a
   * different question: without it the only entry in the file describing the
   * 4b cutover was stamped with a date in August, which reads as "this
   * migration happened when the human last painted". Two events, two fields.
   */
  migratedAt?: string;
}

const MAX_LINEAGE = 8;

export interface MaskSidecar {
  version: number;
  cardId: string;
  variantId: number;
  artworkKey: string;
  width: number;
  height: number;
  /**
   * v4 (4b): the image frame these pixels live in — an id from
   * `data/frames.json`. `canonical` is 504 x 704, the physical card at
   * 8 px/mm; `tcgdex-high` is the pre-4b 490 x 674 authoring raster.
   *
   * INFERRED, NEVER TRUSTED. normalizeSidecar recomputes it on every read,
   * even when the field is already present, so a hand-edited sidecar cannot
   * claim a frame its pixels deny. The raster is the tell — and where the mask
   * PNG is on disk the raster is read from ITS header rather than from the
   * `width`/`height` beside this field, since those are claims too.
   */
  frame: string;
  channel: string;
  /** THE honest label — derived server-side from pixels, never taken on trust. */
  derivation_method: DerivationMethod;
  /** Rollup of derivation_method (recomputed on read; a stale file cannot lie). */
  authorship: Authorship;
  reviewStatus: ReviewStatus;
  /**
   * v5: WHO put these pixels here, recorded by the server from an identity it
   * had already verified. Absent on v1–v4, where absence is historical fact.
   * A client may never supply it — see `functions/_lib/validate.ts`.
   */
  author?: AuthorIdentity | null;
  /**
   * v5: a writer's explicit "this is exemplar-grade". Absent until someone
   * with the capability says so. Honoured only when `verifiedBy` still holds
   * the capability at read time — see `deriveTier`.
   */
  verification?: VerificationRecord | null;
  /**
   * v5: DERIVED from (`version`, `author`, `verification`) on every read, the
   * same discipline as `authorship`/`reviewStatus`/`frame`. It is what the
   * exemplar weight table is keyed on, so a file that could name its own tier
   * would be a file that could name its own training weight.
   */
  provenanceTier: ProvenanceTier;
  savedAt: string;
  /** URL of the scan the mask was drawn on — what a generator must consume. */
  artworkUrl: string | null;
  card?: MaskCardContext;
  prior: MaskPrior;
  priorPng?: string;
  diffPng?: string;
  /** RULE-vs-mask (v2 semantics, preserved): how wrong the era rule was. */
  diff?: DiffStats;
  /** HUMAN-vs-parent: what the human changed. Present only on a correction. */
  correction?: CorrectionRecord;
  /** MACHINE-vs-replaced: what a generator overwrote, and how to undo it. */
  supersedes?: SupersededRecord;
  /** Oldest → newest ancestry, this save last. Capped at MAX_LINEAGE. */
  lineage?: LineageEntry[];
}

/**
 * Historical alias. The in-memory shape is version-agnostic on purpose — v1
 * through v4 all normalize to it — so the name carries no version from v4 on.
 * @deprecated use `MaskSidecar`.
 */
export type MaskSidecarV3 = MaskSidecar;

// ── Migration: v1/v2/v3 → v4, on read, without touching disk ───────────────

function asMethod(raw: unknown): DerivationMethod | null {
  return typeof raw === 'string' && (DERIVATION_METHODS as readonly string[]).includes(raw)
    ? (raw as DerivationMethod)
    : null;
}

/**
 * The frame a mask's pixels live in, decided by the PIXELS.
 *
 * The raster is the tell, and it is the only tell that cannot be forged by
 * editing a JSON file: a 490 x 674 record was painted in the pre-4b
 * `tcgdex-high` authoring raster, a 504 x 704 record is canonical, and
 * anything else resolves to `unknown`. Resolution goes through the registry
 * (`data/frames.json`) rather than a literal here, so adding a frame is a data
 * change.
 *
 * Same discipline as `derivation_method`: state the system measured, never
 * state a caller claimed. A sidecar hand-edited to say `canonical` over
 * 490 x 674 pixels gets `tcgdex-high` back.
 */
export function inferFrame(width: number, height: number): string {
  return resolveFrame({ width, height }).frameId;
}

/**
 * The raster a caller can PROVE, because it read it out of the image header.
 * See normalizeSidecar: when this is supplied it beats the JSON's own numbers.
 */
export interface PixelDims {
  width: number;
  height: number;
}

/**
 * Normalize ANY sidecar generation to the current in-memory shape.
 *
 * v1 (no prior) and v2 both carried the hardcoded placeholder
 * `derivation_method: 'hand'`. That placeholder is only TRUE for masks that
 * predate this module — every one of them was drawn by Chey with a Pencil,
 * which is exactly what 'hand' means. So legacy files migrate to 'hand' and
 * that is honest, not a guess. From v3 on the label is computed from pixels.
 *
 * v3 → v4 (4b) adds `frame`. A v3 record has no such field and gets the right
 * one anyway, because the field is INFERRED from width/height rather than read
 * — see inferFrame. v1/v2/v3 compatibility is permanent.
 *
 * Derived fields (authorship / reviewStatus / frame / provenanceTier) are
 * ALWAYS recomputed here, so a hand-edited or stale sidecar can never claim a
 * status, a framing, or a TRAINING WEIGHT that its own contents deny.
 *
 * v4 → v5 (#10) adds `author` and `verification`. A v1–v4 record has neither
 * and normalizes to `owner-verified` anyway, because that is the historical
 * truth rather than a default: the whole committed corpus predates the
 * contribution pipeline and RELICENSE.md records the sole-author fact. From v5
 * on the inference flips to conservative — a record with no `author` is
 * `unattributed`, i.e. weight 0. See `deriveTier`.
 *
 * `pixels` CLOSES THE LAST HOLE IN THAT RULE. Without it, `frame` is inferred
 * from `width`/`height` — which are JSON, i.e. numbers a caller wrote. The
 * doc-comment claim is that "the raster is the tell, and it is the only tell
 * that cannot be forged by editing a JSON file", and that is only true if the
 * raster comes from the PIXELS. So every caller that has the mask PNG in reach
 * reads its header (foil/image-dims.ts, 32 bytes) and passes the result here;
 * it then wins over the JSON for `width`, `height` AND `frame`, because a
 * sidecar that disagrees with its own PNG is wrong about all three.
 *
 * THE PIXEL-LESS CONTEXTS, where the JSON dims remain the fallback and that is
 * the honest answer rather than a shortcut:
 *
 *   1. A sidecar that arrives as a PARSED OBJECT with no file beside it — an
 *      API response being re-normalized, a record pulled out of a manifest, a
 *      unit-test fixture. There is nothing to read.
 *   2. A HALF-RECORD: the `.json` is on disk but the `.png` is missing or
 *      unreadable. The write paths refuse to create one and both migration
 *      paths throw on it, but a corpus can be damaged out of band, and reading
 *      a damaged record must still tell you what it CLAIMS so you can see the
 *      damage.
 *   3. A file in a format `headerDims` does not parse. It returns null rather
 *      than guessing, and a guess from unreadable bytes would be worse than
 *      the claim already in hand.
 *
 * In every one of those the returned `frame` is inferred from a CLAIM, not a
 * measurement — which is exactly why the on-disk reader below always supplies
 * the pixels.
 */
export function normalizeSidecar(raw: unknown, pixels?: PixelDims | null): MaskSidecar | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const s = raw as Record<string, unknown>;
  if (typeof s.cardId !== 'string' || typeof s.width !== 'number' || typeof s.height !== 'number') return null;

  const width = pixels?.width ?? s.width;
  const height = pixels?.height ?? s.height;
  const method = asMethod(s.derivation_method) ?? 'hand';
  const version = typeof s.version === 'number' ? s.version : 1;
  const author = asAuthor(s.author);
  const verification = asVerification(s.verification);
  const out: MaskSidecar = {
    ...(s as unknown as MaskSidecar),
    version,
    width,
    height,
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    // PARSED, not spread: `...s` would carry a hand-edited `author` of any
    // shape straight through, and `deriveTier` would then be reasoning about a
    // value nothing had checked. A block that is not the right shape is not a
    // half-believed block — it is absent, and an absent author on a v5 record
    // is `unattributed`, which is weight 0.
    ...(author ? { author } : { author: null }),
    ...(verification ? { verification } : { verification: null }),
    // The RECORDED author stays null above when the file names none — an
    // inference must not read back as a record — but the TIER is derived from
    // the effective one, because the tier is a judgement and history is
    // evidence for it. `effectiveAuthor` is also what a version bump writes
    // down, so reading and upgrading cannot disagree.
    provenanceTier: deriveTier(
      version,
      effectiveAuthor({
        version,
        author,
        derivation_method: method,
        prior: s.prior as { generator?: { name: string } | null } | undefined,
      }),
      verification,
    ),
    frame: inferFrame(width, height),
    artworkKey: typeof s.artworkKey === 'string' ? s.artworkKey : s.cardId,
    artworkUrl: typeof s.artworkUrl === 'string' ? s.artworkUrl : null,
  };
  return out;
}

const AUTHOR_CHANNELS: readonly AuthorChannel[] = ['writer-direct', 'contribution-pr', 'generator', 'local-cli'];

/**
 * An `author` block, or null.
 *
 * CONSERVATIVE against MALFORMED input, in the direction that costs weight
 * rather than grants it: an unknown `via`, a missing login, anything that is
 * not the shape this module writes, comes back null — on a v5 record that is
 * `unattributed` and weight 0. It is NOT proof against a WELL-FORMED lie: a
 * hand-edit that reproduces the exact shape the server writes (see door 2 in
 * the residual-hole note above, `HISTORICAL_AUTHOR`'s byte-identical twin) is
 * indistinguishable from the real thing by construction. Shape checks stop
 * accidents; the fork-PR review stops forgeries.
 */
function asAuthor(raw: unknown): AuthorIdentity | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const a = raw as Record<string, unknown>;
  if (typeof a.login !== 'string' || a.login.length === 0) return null;
  if (typeof a.via !== 'string' || !(AUTHOR_CHANNELS as readonly string[]).includes(a.via)) return null;
  return { login: a.login, id: typeof a.id === 'number' ? a.id : null, via: a.via as AuthorChannel };
}

/** A `verification` block, or null. Same conservatism — see `asAuthor`. */
function asVerification(raw: unknown): VerificationRecord | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const v = raw as Record<string, unknown>;
  if (typeof v.verifiedBy !== 'string' || v.verifiedBy.length === 0) return null;
  if (v.via !== 'writer-direct' && v.via !== 'local-cli') return null;
  if (typeof v.verifiedAt !== 'string') return null;
  return {
    verifiedBy: v.verifiedBy,
    verifiedById: typeof v.verifiedById === 'number' ? v.verifiedById : null,
    verifiedAt: v.verifiedAt,
    via: v.via,
    note: typeof v.note === 'string' ? v.note : null,
  };
}

/**
 * The mask PNG's OWN raster, from its header. Null when the file is missing or
 * is not a format `headerDims` reads — see normalizeSidecar's pixel-less cases.
 */
export async function readMaskPixelDims(masksDir: string, cardId: string, variantId: string | number): Promise<PixelDims | null> {
  const path = maskPathsIn(masksDir, cardId, variantId).png;
  const fh = await open(path, 'r').catch(() => null);
  if (!fh) return null;
  try {
    const buf = Buffer.alloc(HEADER_BYTES);
    const { bytesRead } = await fh.read(buf, 0, HEADER_BYTES, 0);
    return headerDims(buf.subarray(0, bytesRead));
  } catch {
    return null;
  } finally {
    await fh.close().catch(() => undefined);
  }
}

/** True when the pixels sit in a framing no record covers. */
export function isUnknownFrame(frame: string): boolean {
  return frame === UNKNOWN_FRAME_ID;
}

// ── Method derivation: the label the PIXELS support ────────────────────────

export interface StartingPoint {
  /** What the editor seeded the canvas with. */
  kind: 'layout' | 'window-bake' | 'mask';
  /** The parent mask, when kind === 'mask'. */
  parent?: { cardId: string; variantId: number; sidecar: MaskSidecar | null; png: Buffer };
}

/**
 * Decide the honest method. `painted` is measured, not claimed: the saved
 * alpha is compared to the alpha the starting point actually rasterizes to.
 */
export function deriveMethod(startedFrom: StartingPoint['kind'], parentMethod: DerivationMethod | null, painted: boolean): DerivationMethod {
  if (!painted) {
    // Nothing changed since the seed. If the seed was a mask, this save is a
    // no-op re-save — keep the parent's honest label rather than inventing one.
    return parentMethod ?? 'layout-flatten';
  }
  if (parentMethod === 'ai' || parentMethod === 'ai-corrected') return 'ai-corrected';
  if (parentMethod !== null) return 'hand-refined';
  // Seeded from geometry (era rect or an adjusted window) and painted on:
  // that is a human mask, however it started.
  void startedFrom;
  return 'hand';
}

// ── Pixel helpers ──────────────────────────────────────────────────────────

export function alphaOf(img: RgbaImage): Uint8Array {
  const a = new Uint8Array(img.width * img.height);
  for (let i = 0; i < a.length; i++) a[i] = img.rgba[i * 4 + 3]!;
  return a;
}

export function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

/**
 * BILINEAR resample of an RGBA image — the frame migration's only pixel
 * operation.
 *
 * Bilinear and not the nearest-neighbour sampler the generators use, because a
 * mask is a SOFT-EDGED zone map: the shader reads it through `uMaskFeather`
 * 0.008 UV of blur, and every boundary carries a real antialiasing ramp that
 * `countPaintedOver`'s seam tolerance and `deriveMethod` both depend on.
 * Nearest neighbour would quantise that ramp into a staircase and turn a
 * resample into an edit. Canonical space is larger than the 490 x 674
 * authoring raster in BOTH axes, so this only ever interpolates up.
 *
 * All four channels go through it. Only alpha is the mask; RGB is the display
 * tint, which is a flat colour in every mask the editor writes, so bilinear on
 * it is a no-op in practice and correct if it ever is not.
 */
export function resampleRgba(src: RgbaImage, dw: number, dh: number): RgbaImage {
  const { width: sw, height: sh, rgba: s } = src;
  if (sw === dw && sh === dh) return { width: dw, height: dh, rgba: Uint8Array.from(s) };
  const out = new Uint8Array(dw * dh * 4);
  // Map destination pixel CENTRES back to source pixel centres, so the two
  // rasters describe the same continuous card rather than the same corner.
  const fx = sw / dw;
  const fy = sh / dh;
  for (let y = 0; y < dh; y++) {
    const sy = (y + 0.5) * fy - 0.5;
    const y0 = Math.max(0, Math.min(sh - 1, Math.floor(sy)));
    const y1 = Math.max(0, Math.min(sh - 1, y0 + 1));
    const wy = Math.max(0, Math.min(1, sy - y0));
    for (let x = 0; x < dw; x++) {
      const sx = (x + 0.5) * fx - 0.5;
      const x0 = Math.max(0, Math.min(sw - 1, Math.floor(sx)));
      const x1 = Math.max(0, Math.min(sw - 1, x0 + 1));
      const wx = Math.max(0, Math.min(1, sx - x0));
      const i00 = (y0 * sw + x0) * 4;
      const i01 = (y0 * sw + x1) * 4;
      const i10 = (y1 * sw + x0) * 4;
      const i11 = (y1 * sw + x1) * 4;
      const o = (y * dw + x) * 4;
      for (let c = 0; c < 4; c++) {
        const top = s[i00 + c]! * (1 - wx) + s[i01 + c]! * wx;
        const bot = s[i10 + c]! * (1 - wx) + s[i11 + c]! * wx;
        out[o + c] = Math.round(top * (1 - wy) + bot * wy);
      }
    }
  }
  return { width: dw, height: dh, rgba: out };
}

/**
 * Human-vs-parent correction metrics + a spatial grid. Uses the same
 * foil threshold and diff PNG colors as the rule diff, so the two artifacts
 * are read the same way (GREEN = added, RED = removed).
 */
export function correctionMetrics(
  saved: RgbaImage,
  parentAlpha: Uint8Array,
  gridSize = 4,
): { png: Buffer; stats: DiffStats; changedPx: number; changedFraction: number; bbox: [number, number, number, number] | null; grid: CorrectionGrid } {
  const { width, height } = saved;
  const { png, stats } = diffMask(saved, parentAlpha);
  const cells = new Array<number>(gridSize * gridSize).fill(0);
  const cellCounts = new Array<number>(gridSize * gridSize).fill(0);
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;
  let changedPx = 0;
  for (let y = 0; y < height; y++) {
    const gy = Math.min(gridSize - 1, Math.floor((y / height) * gridSize));
    for (let x = 0; x < width; x++) {
      const i = y * width + x;
      const gx = Math.min(gridSize - 1, Math.floor((x / width) * gridSize));
      const cell = gy * gridSize + gx;
      cellCounts[cell]!++;
      const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
      const inParent = parentAlpha[i]! >= FOIL_THRESHOLD;
      if (inSaved === inParent) continue;
      changedPx++;
      cells[cell]!++;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  const total = width * height;
  // UV y-up bbox — same space as prior.rect, so a generator can use it directly.
  const bbox: [number, number, number, number] | null =
    maxX < 0
      ? null
      : [
          Number((minX / width).toFixed(4)),
          Number((1 - (maxY + 1) / height).toFixed(4)),
          Number(((maxX - minX + 1) / width).toFixed(4)),
          Number(((maxY - minY + 1) / height).toFixed(4)),
        ];
  return {
    png,
    stats,
    changedPx,
    changedFraction: Number((changedPx / total).toFixed(6)),
    bbox,
    grid: {
      size: gridSize,
      cells: cells.map((c, i) => Number((c / (cellCounts[i] || 1)).toFixed(3))),
    },
  };
}

/**
 * Count pixels the human actually painted, relative to a starting alpha plane.
 *
 * `seamTolerant` matters when the start is a RASTERIZED RECT rather than a
 * stored mask. The editor bakes the window with canvas `roundRect` + `fill`;
 * this module rasterizes the same rect from a signed-distance field. Both are
 * correct, and both put ~0.5 coverage on the true edge — so they legitimately
 * disagree in the one-pixel antialiasing band. Measured on the WOTC window at
 * 490×674: 389 of 330,260 px cross the foil threshold differently, and ALL 389
 * sit in that band. Counting them would stamp every unpainted Flatten as
 * `hand`, which is exactly the lie sidecar v3 exists to stop.
 *
 * So a pixel counts as painted only where the SEED IS UNAMBIGUOUS — its 3×3
 * neighbourhood is entirely foil or entirely empty. A brush stroke (>= 4 px)
 * always clears that bar; a rasterizer seam never does. The residual blind
 * spot is a human painting a 1-px line exactly along the window edge, which is
 * both implausible and harmless (the next real stroke reclassifies the save).
 */
export function countPaintedOver(
  saved: RgbaImage,
  seed: Uint8Array,
  width: number,
  height: number,
  seamTolerant: boolean,
): number {
  let n = 0;
  for (let i = 0; i < seed.length; i++) {
    const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
    const inSeed = seed[i]! >= FOIL_THRESHOLD;
    if (inSaved === inSeed) continue;
    if (!seamTolerant) {
      n++;
      continue;
    }
    const x = i % width;
    const y = (i / width) | 0;
    let hi = 0;
    let lo = 0;
    for (let dy = -1; dy <= 1; dy++) {
      const ny = y + dy;
      if (ny < 0 || ny >= height) continue;
      for (let dx = -1; dx <= 1; dx++) {
        const nx = x + dx;
        if (nx < 0 || nx >= width) continue;
        if (seed[ny * width + nx]! >= FOIL_THRESHOLD) hi++;
        else lo++;
      }
    }
    if (hi === 0 || lo === 0) n++; // seed unambiguous here ⇒ a real edit
  }
  return n;
}

// ── Paths ──────────────────────────────────────────────────────────────────

export interface MaskPaths {
  dir: string;
  png: string;
  json: string;
  prior: string;
  diff: string;
  parent: string;
  parentDiff: string;
}

export function maskPathsIn(masksDir: string, cardId: string, variantId: string | number): MaskPaths {
  const dir = join(masksDir, cardId);
  return {
    dir,
    png: join(dir, `${variantId}.png`),
    json: join(dir, `${variantId}.json`),
    prior: join(dir, `${variantId}.prior.png`),
    diff: join(dir, `${variantId}.diff.png`),
    parent: join(dir, `${variantId}.parent.png`),
    parentDiff: join(dir, `${variantId}.parent.diff.png`),
  };
}

/**
 * Read a sidecar off disk, resolved against ITS OWN PIXELS.
 *
 * The mask PNG is right there, so this is the context where "the raster is the
 * tell" can actually be honoured: the header is read (32 bytes) and beats
 * whatever the JSON says about its own dimensions. A `.json` whose `width` was
 * hand-edited, or written stale by a client, reads back with the frame the
 * pixels support. A missing/unreadable PNG falls back to the JSON — see
 * normalizeSidecar case 2.
 */
export async function readSidecarFile(
  masksDir: string,
  cardId: string,
  variantId: string | number,
): Promise<MaskSidecar | null> {
  const text = await readFile(maskPathsIn(masksDir, cardId, variantId).json, 'utf8').catch(() => null);
  if (text === null) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(text) as unknown;
  } catch {
    return null;
  }
  return normalizeSidecar(parsed, await readMaskPixelDims(masksDir, cardId, variantId));
}

/** Where a generator run parks the mask it replaced. Committed with the corpus. */
export function archiveDirName(variantId: string | number, runId: string): string {
  return join('superseded', `${variantId}.${runId.replace(/[^A-Za-z0-9._-]/g, '_')}`);
}

/**
 * The archive is SELF-DESCRIBING on disk (`archive.json`), not merely pointed
 * at by the sidecar. That matters: once Chey corrects a generated mask the live
 * sidecar stops being about the supersede, but his original must still be one
 * command away. So the undo reads the manifest from the archive itself.
 */
export interface ArchiveManifest {
  version: 1;
  cardId: string;
  variantId: number;
  runId: string;
  archivedAt: string;
  /** The replaced mask's method — what a restore puts back. */
  method: DerivationMethod;
  /** basename → sha256 of the archived bytes. */
  files: Record<string, string>;
}

const ARCHIVE_MANIFEST = 'archive.json';

/**
 * Copy every artifact currently on disk into the run's archive, VERBATIM, and
 * drop a manifest beside them. Returns basename → sha256 so a restore can
 * prove it put back the same BYTES, not a re-serialization that merely looks
 * equivalent.
 */
async function archiveExisting(
  paths: MaskPaths,
  cardId: string,
  variantId: string,
  runId: string,
  method: DerivationMethod,
): Promise<Record<string, string>> {
  const dir = join(paths.dir, archiveDirName(variantId, runId));
  mkdirSync(dir, { recursive: true });
  const files: Record<string, string> = {};
  for (const src of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    const buf = await readFile(src).catch(() => null);
    if (!buf) continue;
    const name = basename(src);
    await writeFile(join(dir, name), buf);
    files[name] = sha256(buf);
  }
  const manifest: ArchiveManifest = {
    version: 1,
    cardId,
    variantId: Number(variantId),
    runId,
    archivedAt: new Date().toISOString(),
    method,
    files,
  };
  await writeFile(join(dir, ARCHIVE_MANIFEST), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return files;
}

export interface FoundArchive {
  cardId: string;
  variantId: number;
  runId: string;
  /** Absolute path of the archive directory. */
  dir: string;
  manifest: ArchiveManifest;
}

/** Every generator archive on disk, optionally filtered to one run. */
export async function findArchives(masksDir: string, runId?: string | null): Promise<FoundArchive[]> {
  const out: FoundArchive[] = [];
  const cardDirs = await readdir(masksDir).catch(() => [] as string[]);
  for (const cardId of cardDirs) {
    if (cardId === 'codified') continue;
    const supDir = join(masksDir, cardId, 'superseded');
    const runs = await readdir(supDir).catch(() => [] as string[]);
    for (const r of runs) {
      const dir = join(supDir, r);
      const raw = await readFile(join(dir, ARCHIVE_MANIFEST), 'utf8').catch(() => null);
      if (!raw) continue;
      const manifest = JSON.parse(raw) as ArchiveManifest;
      if (runId && manifest.runId !== runId) continue;
      out.push({ cardId, variantId: manifest.variantId, runId: manifest.runId, dir, manifest });
    }
  }
  return out.sort((a, b) => (a.cardId === b.cardId ? a.variantId - b.variantId : a.cardId < b.cardId ? -1 : 1));
}

export interface RestoreResult {
  cardId: string;
  variantId: number;
  runId: string;
  /** Files put back, with the sha256 that was verified on each. */
  restored: { file: string; sha256: string }[];
  /** The method the restored mask carries — i.e. what Chey gets back. */
  method: DerivationMethod;
}

/**
 * Put back exactly what a generator run replaced. Byte-for-byte: every file is
 * read from the archive and re-hashed against the manifest recorded at
 * supersede time, and the WHOLE archive is verified before a single live file
 * is deleted — so a corrupt archive can never turn "undo" into "lose both".
 */
export async function restoreArchive(masksDir: string, found: FoundArchive): Promise<RestoreResult> {
  const paths = maskPathsIn(masksDir, found.cardId, found.variantId);
  const staged: { name: string; buf: Buffer; sha: string }[] = [];
  for (const [name, sha] of Object.entries(found.manifest.files)) {
    const buf = await readFile(join(found.dir, name));
    const got = sha256(buf);
    if (got !== sha) throw new Error(`archive ${found.dir}/${name} is corrupt (sha256 ${got} != ${sha})`);
    staged.push({ name, buf, sha });
  }
  if (!staged.some((s) => s.name === `${found.variantId}.png`)) {
    throw new Error(`archive ${found.dir} has no ${found.variantId}.png — refusing to delete the live mask`);
  }

  for (const f of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    await unlink(f).catch(() => undefined);
  }
  for (const s of staged) await writeFile(join(paths.dir, s.name), s.buf);
  await rm(found.dir, { recursive: true, force: true });
  const left = await readdir(join(paths.dir, 'superseded')).catch(() => null);
  if (left && left.length === 0) await rm(join(paths.dir, 'superseded'), { recursive: true, force: true });

  const back = await readSidecarFile(masksDir, found.cardId, found.variantId);
  return {
    cardId: found.cardId,
    variantId: found.variantId,
    runId: found.runId,
    restored: staged.map((s) => ({ file: s.name, sha256: s.sha })),
    method: back?.derivation_method ?? found.manifest.method,
  };
}

// ── Frame migration (4b): the corpus moves rasters, nobody repaints ────────
//
// A THIRD kind of write, deliberately distinct from both `correction` (a human
// edited this) and `supersedes` (a generator replaced this). Neither describes
// what happens here: the mask is resampled from one frame into another and the
// SHAPE IT ENCODES IS UNCHANGED. So `derivation_method` does not move — a
// `hand` mask stays `hand`, because nobody repainted anything — and neither
// does `savedAt`, because the alias rule picks the newest save per
// (cardId, scope) and re-stamping it would misreport when the human worked.
//
// It reuses `archiveExisting` rather than growing a second archival route: the
// pre-migration bytes go into `superseded/<variantId>.<runId>/` verbatim with a
// sha256 per file, BEFORE anything is replaced, and `restoreArchive` undoes the
// whole pass with `revert --run-id`.

export interface FrameMigrationInput {
  masksDir: string;
  cardId: string;
  variantId: string | number;
  /** Frame id the pixels are moving INTO (an id in data/frames.json). */
  toFrame: string;
  /** Target raster — must be the target frame's raster. */
  width: number;
  height: number;
  /** Groups the whole pass. The handle `revert --run-id` uses. */
  runId: string;
}

export interface FrameMigrationResult {
  cardId: string;
  variantId: number;
  from: { frame: string; width: number; height: number };
  to: { frame: string; width: number; height: number };
  /** basename → sha256 of the pre-migration bytes, verified into the archive. */
  archive: Record<string, string>;
  archiveDir: string;
  /** Unchanged by construction — asserted, not assumed. */
  method: DerivationMethod;
  sidecar: MaskSidecar;
  /** Correction metrics before and after, when this mask carries a correction. */
  correctionDrift: { before: number; after: number } | null;
}

export async function migrateMaskFrame(input: FrameMigrationInput): Promise<FrameMigrationResult> {
  const { masksDir, cardId, runId, toFrame, width, height } = input;
  const variantId = String(input.variantId);
  const paths = maskPathsIn(masksDir, cardId, variantId);

  const existing = await readSidecarFile(masksDir, cardId, variantId);
  if (!existing) throw new Error(`${cardId}/${variantId} has no readable sidecar`);
  const livePng = await readFile(paths.png).catch(() => null);
  if (!livePng) throw new Error(`${cardId}/${variantId} has a sidecar but no mask PNG — refusing to migrate a half-record`);

  if (existing.supersedes) {
    // No live sidecar carries one today. Carrying the block forward unchanged
    // would leave its recorded parent sha256 pointing at a file this pass is
    // about to resample, i.e. a provenance record that no longer verifies.
    // Refuse loudly rather than emit that.
    throw new Error(
      `${cardId}/${variantId} carries a \`supersedes\` block; frame migration of a superseded record is not ` +
        'implemented, because resampling its .parent.png would falsify supersedes.parent.sha256. Restore or ' +
        'accept the supersede first (revert --run-id), then migrate.',
    );
  }

  const saved = decodePng(livePng);
  if (saved.width === width && saved.height === height && existing.frame === toFrame) {
    return {
      cardId,
      variantId: Number(variantId),
      from: { frame: existing.frame, width: saved.width, height: saved.height },
      to: { frame: toFrame, width, height },
      archive: {},
      archiveDir: '',
      method: existing.derivation_method,
      sidecar: existing,
      correctionDrift: null,
    };
  }

  // 1. ARCHIVE FIRST, while the originals are still on disk. Same route the
  //    supersede path uses, so there is one archival code path, not two.
  const archive = await archiveExisting(paths, cardId, variantId, runId, existing.derivation_method);

  // 2. The mask itself.
  const migrated = resampleRgba(saved, width, height);
  const migratedPng = encodePng(migrated);

  // 3. The rule artifacts. The prior is FRACTIONAL — rects are fractions of the
  //    card face, invariant under the resample — so it is re-rasterized at the
  //    new raster rather than resampled. Regenerating is exact; resampling a
  //    rasterization is a copy of a copy.
  const priorPng = renderPriorPng(width, height, existing.prior);
  const ruleAlpha = rasterizePriorAlpha(width, height, existing.prior);
  const { png: diffPng, stats } = diffMask(migrated, ruleAlpha);

  // 4. The correction, when there is one. Both sides are now canonical, so the
  //    metrics are RECOMPUTED — they have to describe the pixels actually on
  //    disk. The drift is reported rather than hidden: the human's edit is the
  //    same edit, measured on a finer grid.
  let correction: CorrectionRecord | undefined;
  let correctionDrift: FrameMigrationResult['correctionDrift'] = null;
  if (existing.correction) {
    const parentBuf = await readFile(paths.parent).catch(() => null);
    if (!parentBuf) {
      throw new Error(`${cardId}/${variantId} claims a correction but ${basename(paths.parent)} is missing`);
    }
    const parentMigrated = resampleRgba(decodePng(parentBuf), width, height);
    const parentPngBytes = encodePng(parentMigrated);
    const m = correctionMetrics(migrated, alphaOf(parentMigrated));
    correction = {
      ...existing.correction,
      parent: { ...existing.correction.parent, sha256: sha256(parentPngBytes) },
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    correctionDrift = { before: existing.correction.agreement, after: m.stats.agreement };
    await writeFile(paths.parent, parentPngBytes);
    await writeFile(paths.parentDiff, m.png);
  }

  // 5. The lineage entry. It says what this was — a frame migration — and it
  //    carries the method FORWARD rather than inventing one.
  const lineage: LineageEntry[] = [
    ...(existing.lineage ?? [
      {
        method: existing.derivation_method,
        savedAt: existing.savedAt ?? null,
        source: existing.prior?.source ?? 'layout',
        generator: existing.prior?.generator
          ? {
              name: existing.prior.generator.name,
              version: existing.prior.generator.version,
              runId: existing.prior.generator.runId,
            }
          : null,
      },
    ]),
    {
      method: existing.derivation_method,
      // The HUMAN's save date, carried forward unchanged — see LineageEntry.
      savedAt: existing.savedAt ?? null,
      source: existing.prior?.source ?? 'layout',
      generator: null,
      frameMigration: { from: existing.frame, to: toFrame, runId },
      // …and the date of THIS event, which is a different one.
      migratedAt: new Date().toISOString(),
    },
  ].slice(-MAX_LINEAGE);

  const sidecar: MaskSidecar = {
    ...existing,
    version: SIDECAR_VERSION,
    width,
    height,
    frame: toFrame,
    // Unchanged on purpose. Nobody repainted anything, and the alias rule picks
    // the newest save per (cardId, scope).
    derivation_method: existing.derivation_method,
    authorship: AUTHORSHIP_BY_METHOD[existing.derivation_method],
    reviewStatus: REVIEW_BY_METHOD[existing.derivation_method],
    // Carried forward for the same reason `derivation_method` is: nobody
    // repainted anything and nobody re-reviewed anything, so neither the author
    // nor the verification changed. `authorForUpgrade` is what stops the
    // VERSION STAMP from quietly demoting the record — see its doc comment.
    author: authorForUpgrade(existing),
    verification: existing.verification ?? null,
    provenanceTier: deriveTier(SIDECAR_VERSION, authorForUpgrade(existing), existing.verification),
    savedAt: existing.savedAt,
    diff: stats,
    ...(correction ? { correction } : {}),
    lineage,
  };

  mkdirSync(paths.dir, { recursive: true });
  await writeFile(paths.png, migratedPng);
  await writeFile(paths.prior, priorPng);
  await writeFile(paths.diff, diffPng);
  await writeFile(paths.json, JSON.stringify(sidecar, null, 2) + '\n', 'utf8');

  if (sidecar.derivation_method !== existing.derivation_method) {
    throw new Error('invariant violated: a frame migration changed derivation_method');
  }

  return {
    cardId,
    variantId: Number(variantId),
    from: { frame: existing.frame, width: saved.width, height: saved.height },
    to: { frame: toFrame, width, height },
    archive,
    archiveDir: archiveDirName(variantId, runId),
    method: existing.derivation_method,
    sidecar,
    correctionDrift,
  };
}

// ── THE single write path ──────────────────────────────────────────────────

export interface WriteMaskInput {
  masksDir: string;
  cardId: string;
  variantId: string;
  /** The mask PNG bytes (alpha = coverage). */
  png: Buffer;
  width: number;
  height: number;
  /** The deterministic era-rule prior (always recorded — keeps the codify score alive). */
  prior: MaskPrior;
  /** What the canvas was seeded with. Only affects which pixels `painted` is measured against. */
  startedFrom: StartingPoint['kind'];
  /** Claimed parent (cardId/variantId) when startedFrom === 'mask'. */
  parentRef?: { cardId: string; variantId: number } | null;
  artworkUrl?: string | null;
  card?: MaskCardContext;
  /**
   * ONLY a real generator may claim a machine label, and only by handing over
   * a full identity. No identity ⇒ the method is derived from pixels.
   */
  machine?: GeneratorIdentity | null;
  /**
   * WHO IS SAVING, from an identity the caller has ALREADY VERIFIED.
   *
   * Same trust model as `machine` above and for the same reason: the route
   * knows the answer (a signed session cookie), the client does not get to
   * assert one, and the field is the only way to say it. Omitting it is not a
   * shortcut — from v5 on it produces an `unattributed` record at weight 0, and
   * `functions/_lib/validate.ts` refuses any submission that tries to supply
   * one itself.
   *
   * The generator paths pass `{ login: <generator name>, id: null, via:
   * 'generator' }`, which reads back as `unattributed` rather than as a person.
   */
  author?: AuthorIdentity | null;
  /**
   * Machine writes only: explicit consent to land on top of a mask that is
   * already there — including a HUMAN one. Without it, a generator write over
   * anything but its own unreviewed output THROWS. With it, every artifact the
   * mask had is archived verbatim under `superseded/<variantId>.<runId>/`,
   * `.parent.png` keeps the replaced pixels, and `supersedes` records the
   * sha256s that make `restoreSuperseded()` an exact undo.
   */
  supersede?: { runId: string } | null;
}

/**
 * Write a mask + every provenance artifact, stamping the method the pixels
 * support. Used by the foil-lab PUT route AND by generators — one path, so
 * "every write path stamps honestly" is structural, not a promise.
 */
export async function writeMaskRecord(input: WriteMaskInput): Promise<MaskSidecar> {
  const { masksDir, cardId, variantId, png, width, height, prior } = input;
  const paths = maskPathsIn(masksDir, cardId, variantId);
  const saved = decodePng(png);
  if (saved.width !== width || saved.height !== height) throw new Error('png dimensions do not match width/height');

  // ── THE FRAME GATE (4b) ──
  //
  // Derived from the pixels, never claimed. An unregistered raster is not a
  // mask you save carefully — it is a mask you do not save: a stencil cut for
  // a picture nobody can name is worse than no stencil, because nothing
  // downstream can tell it apart from a good one.
  const frameRes = resolveFrame({ width, height, eraId: prior?.eraId ?? null });
  assertAuthorable(frameRes);
  const frame = frameRes.frameId;

  // ── The parent: what this save is replacing / was painted on top of ──
  //
  // SAFETY RULE: whatever the client claims, if the file at the target path is
  // unreviewed machine output ('ai'), it IS the parent. Otherwise a client that
  // forgot to report the parent would silently launder an AI mask into 'hand'
  // and the correction signal — the whole point — would be lost.
  const existing = await readSidecarFile(masksDir, cardId, variantId);
  let parentRef = input.parentRef ?? null;
  if (existing?.derivation_method === 'ai') parentRef = { cardId, variantId: Number(variantId) };

  // A generator landing on an existing mask must say so out loud. Silence used
  // to mean "overwrite", which is how human work disappears.
  const supersede = input.machine ? (input.supersede ?? null) : null;
  if (input.machine && existing && !supersede) {
    throw new Error(
      `${cardId}/${variantId} already has a ${existing.derivation_method} mask. A generator may only replace it with ` +
        'an explicit supersede { runId } — which archives the original byte-for-byte so `revert --run-id` undoes it.',
    );
  }

  let parentSidecar: MaskSidecar | null = null;
  let parentPngBuf: Buffer | null = null;
  if (parentRef) {
    const pp = maskPathsIn(masksDir, parentRef.cardId, parentRef.variantId);
    parentPngBuf = await readFile(pp.png).catch(() => null);
    if (parentPngBuf) parentSidecar = await readSidecarFile(masksDir, parentRef.cardId, parentRef.variantId);
    else parentRef = null; // claimed a parent that isn't on disk — treat as none
  }

  // ── `painted`: measured against the pixels the starting point produces ──
  let startingAlpha: Uint8Array;
  let seamTolerant: boolean;
  if (parentPngBuf) {
    // Both masks came out of the SAME rasterizer (the editor canvas), so an
    // exact comparison is correct — every differing pixel is a human stroke.
    startingAlpha = alphaOf(decodePng(parentPngBuf));
    seamTolerant = false;
  } else {
    // Geometry seed. A window bake starts from the ADJUSTED rect when there is
    // one (that is what MaskEditor/Flatten rasterize); otherwise the era rule.
    const geom: MaskPrior =
      input.startedFrom === 'window-bake' && prior.window
        ? { ...prior, rect: prior.window.rect, radius: prior.window.radius }
        : prior;
    startingAlpha = rasterizePriorAlpha(width, height, geom);
    seamTolerant = true;
  }
  const painted = countPaintedOver(saved, startingAlpha, width, height, seamTolerant) > 0;

  const machine = input.machine ?? null;
  // A generator identity IS the author when there is no human one — otherwise a
  // machine write would land as `unattributed`-because-nobody-said, which reads
  // the same as a damaged record. Say it out loud instead.
  const author: AuthorIdentity | null =
    input.author ?? (machine ? { login: machine.name, id: null, via: 'generator' } : null);
  const method: DerivationMethod = machine
    ? 'ai'
    : deriveMethod(input.startedFrom, parentSidecar?.derivation_method ?? (parentPngBuf ? 'hand' : null), painted);

  // ── prior.source + generator carry-forward ──
  const inheritedGenerator =
    machine ??
    parentSidecar?.prior?.generator ??
    (parentSidecar?.correction?.parent.generator ?? null);
  const source: MaskPrior['source'] = machine
    ? 'ai'
    : parentSidecar && (parentSidecar.derivation_method === 'ai' || parentSidecar.derivation_method === 'ai-corrected')
      ? 'ai'
      : parentRef
        ? 'mask'
        : input.startedFrom === 'window-bake' && prior.window
          ? 'window'
          : 'layout';

  const replacedRef =
    parentRef && parentSidecar
      ? { cardId: parentRef.cardId, variantId: parentRef.variantId, sidecar: parentSidecar }
      : supersede && existing
        ? { cardId, variantId: Number(variantId), sidecar: existing }
        : null;

  const fullPrior: MaskPrior = {
    ...prior,
    source,
    ...(inheritedGenerator ? { generator: inheritedGenerator } : {}),
    ...(replacedRef
      ? {
          parentMask: {
            cardId: replacedRef.cardId,
            variantId: replacedRef.variantId,
            savedAt: replacedRef.sidecar.savedAt ?? null,
            method: replacedRef.sidecar.derivation_method,
          },
        }
      : {}),
  };

  // ── Rule-vs-mask artifacts (v2 semantics — the codify score) ──
  const ruleAlpha = rasterizePriorAlpha(width, height, prior);
  const priorPng = renderPriorPng(width, height, prior);
  const { png: diffPng, stats } = diffMask(saved, ruleAlpha);

  // ── Human-vs-parent artifacts (the correction signal) ──
  let correction: CorrectionRecord | undefined;
  if (parentRef && parentPngBuf && painted && !machine) {
    const m = correctionMetrics(saved, alphaOf(decodePng(parentPngBuf)));
    correction = {
      parent: {
        cardId: parentRef.cardId,
        variantId: parentRef.variantId,
        savedAt: parentSidecar?.savedAt ?? null,
        method: parentSidecar?.derivation_method ?? 'hand',
        sha256: sha256(parentPngBuf),
        generator: parentSidecar?.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, parentPngBuf);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Machine-vs-replaced artifacts + the verbatim undo archive ──
  //
  // Order matters: archive FIRST (while the originals are still on disk),
  // then write the parent pixels + change map, then the sidecar. A crash
  // between steps leaves the archive intact, which is the safe direction.
  let supersedes: SupersededRecord | undefined;
  if (supersede && existing) {
    const replacedPng = await readFile(paths.png).catch(() => null);
    if (!replacedPng) {
      throw new Error(`${cardId}/${variantId} has a sidecar but no mask PNG — refusing to supersede a half-record`);
    }
    const archive = await archiveExisting(paths, cardId, variantId, supersede.runId, existing.derivation_method);
    const m = correctionMetrics(saved, alphaOf(decodePng(replacedPng)));
    supersedes = {
      parent: {
        cardId,
        variantId: Number(variantId),
        savedAt: existing.savedAt ?? null,
        method: existing.derivation_method,
        sha256: sha256(replacedPng),
        generator: existing.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      runId: supersede.runId,
      archiveDir: archiveDirName(variantId, supersede.runId),
      archive,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, replacedPng);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Lineage: the parent's chain (which already ENDS with the parent's own
  // entry — don't append it twice) plus this save. Pre-v3 parents have no
  // lineage array, so synthesize their single entry from what they do record.
  const savedAt = new Date().toISOString();
  const ancestor = parentSidecar ?? (supersede ? existing : null);
  const parentLineage: LineageEntry[] = ancestor
    ? (ancestor.lineage ?? [
        {
          method: ancestor.derivation_method,
          savedAt: ancestor.savedAt ?? null,
          source: ancestor.prior?.source ?? 'layout',
          generator: ancestor.prior?.generator
            ? {
                name: ancestor.prior.generator.name,
                version: ancestor.prior.generator.version,
                runId: ancestor.prior.generator.runId,
              }
            : null,
        },
      ])
    : [];
  const lineage: LineageEntry[] = [
    ...parentLineage,
    {
      method,
      savedAt,
      source,
      generator: machine ? { name: machine.name, version: machine.version, runId: machine.runId } : null,
    },
  ].slice(-MAX_LINEAGE);

  const sidecar: MaskSidecar = {
    version: SIDECAR_VERSION,
    cardId,
    variantId: Number(variantId),
    // Identity rule (unchanged since v2): a mask belongs to the card's SCAN.
    // The FRAME is not part of that identity and never enters an alias key:
    // one mask per (cardId, scope), stored in canonical space, transformed out
    // to whatever image it is drawn over.
    artworkKey: cardId,
    width,
    height,
    frame,
    channel: 'alpha',
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    author,
    // A NEW SAVE IS NOT VERIFIED, whoever made it. When the author holds the
    // writer capability `deriveTier` returns `owner-verified` from the author
    // alone, so a writer's save needs no block; when they do not, a block
    // carried forward from the mask that USED to be here would be a
    // verification of pixels the verifier never saw. The only thing that
    // writes one is `writeVerification`, after somebody looked.
    verification: null,
    provenanceTier: deriveTier(SIDECAR_VERSION, author, null),
    savedAt,
    artworkUrl: input.artworkUrl ?? existing?.artworkUrl ?? null,
    ...(input.card ? { card: input.card } : existing?.card ? { card: existing.card } : {}),
    prior: fullPrior,
    priorPng: `${variantId}.prior.png`,
    diffPng: `${variantId}.diff.png`,
    diff: stats,
    ...(correction ? { correction } : {}),
    ...(supersedes ? { supersedes } : {}),
    lineage,
  };

  mkdirSync(paths.dir, { recursive: true });
  await writeFile(paths.png, png);
  await writeFile(paths.prior, priorPng);
  await writeFile(paths.diff, diffPng);
  // A save with neither a correction nor a supersede must not leave a STALE
  // parent artifact behind.
  if (!correction && !supersedes) {
    await unlink(paths.parent).catch(() => undefined);
    await unlink(paths.parentDiff).catch(() => undefined);
  }
  await writeFile(paths.json, JSON.stringify(sidecar, null, 2) + '\n', 'utf8');
  return sidecar;
}

// ── Promotion: the only thing that grants exemplar weight ──────────────────
//
// A fourth kind of write, and the smallest one in the file: it touches the
// `.json` and nothing else, because verification is a statement ABOUT pixels
// and not a change TO them. The mask, the prior, the diff and any correction
// artifacts are byte-identical afterwards — `sha256` over `<variantId>.png` is
// the same before and after, which is what makes "verify" reviewable as a
// one-line diff rather than as a re-save.
//
// WHY IT IS A FUNCTION HERE RATHER THAN A FIELD SOMEBODY EDITS. The whole
// argument of this module is that a label nobody measured is worse than no
// label. `verification` is the one field in the sidecar that is genuinely an
// ASSERTION rather than a measurement — no arrangement of pixels can prove a
// human looked at them — so the compensating discipline is that it can only be
// written by a route that has already re-derived the verifier's identity from a
// signed session cookie, and that `deriveTier` then re-checks the login against
// the writer capability on EVERY read. A hand-edited block naming somebody
// without the capability is not half-believed; it is ignored.

export interface VerifyMaskInput {
  masksDir: string;
  cardId: string;
  variantId: string | number;
  /** The verifier, from an identity the CALLER already verified. */
  verifier: { login: string; id: number | null };
  /** The route asserting it. Both are writer-gated; nothing else may pass. */
  via: VerificationRecord['via'];
  /** The verifier's own words about why. Optional, and kept verbatim. */
  note?: string | null;
  /** Clock injection for tests. */
  now?: () => Date;
}

export class NotAWriter extends Error {}

export interface VerifyMaskResult {
  sidecar: MaskSidecar;
  /** True when the record already sat at `owner-verified` and nothing changed. */
  unchanged: boolean;
  /** The tier before and after, so a caller can report the promotion honestly. */
  from: ProvenanceTier;
  to: ProvenanceTier;
}

/**
 * Record a writer's verification of an existing mask, promoting its tier.
 *
 * REFUSES rather than writes an ignorable block when the verifier does not hold
 * the writer capability. A record that would be disbelieved on the next read is
 * not a record — it is a file that makes a reviewer think something happened.
 */
export async function verifyMaskRecord(input: VerifyMaskInput): Promise<VerifyMaskResult> {
  const { masksDir, cardId, verifier, via } = input;
  const variantId = String(input.variantId);
  if (!isWriter(verifier.login)) {
    throw new NotAWriter(
      `${verifier.login} does not hold the writer capability, so a verification signed by them would be ignored ` +
        'on every read (see deriveTier). Refusing to write one.',
    );
  }
  const paths = maskPathsIn(masksDir, cardId, variantId);
  const existing = await readSidecarFile(masksDir, cardId, variantId);
  if (!existing) throw new Error(`${cardId}/${variantId} has no readable sidecar`);

  const from = existing.provenanceTier;
  if (from === 'owner-verified' && existing.verification) {
    return { sidecar: existing, unchanged: true, from, to: from };
  }

  const verification: VerificationRecord = {
    verifiedBy: verifier.login,
    verifiedById: verifier.id,
    verifiedAt: (input.now?.() ?? new Date()).toISOString(),
    via,
    note: input.note ?? null,
  };
  // The raw file is re-read and SPREAD OVER, rather than the normalized value
  // being re-serialized: normalization fills derived fields and drops nothing,
  // but writing the normalized shape back would rewrite every key in the file
  // and turn a one-line promotion into a whole-file diff.
  const rawText = await readFile(paths.json, 'utf8');
  const raw = JSON.parse(rawText) as Record<string, unknown>;
  const author = authorForUpgrade(existing);
  const upgraded = {
    ...raw,
    version: SIDECAR_VERSION,
    ...(author ? { author } : {}),
    verification,
    provenanceTier: deriveTier(SIDECAR_VERSION, author, verification),
  };
  await writeFile(paths.json, JSON.stringify(upgraded, null, 2) + '\n', 'utf8');

  const back = await readSidecarFile(masksDir, cardId, variantId);
  if (!back || back.provenanceTier !== 'owner-verified') {
    throw new Error('invariant violated: a verification was written that does not read back as owner-verified');
  }
  return { sidecar: back, unchanged: false, from, to: back.provenanceTier };
}
