// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Chey Rasmussen
// foil/provenance.ts — sidecar v4: honest mask provenance + the AI learning loop.
//
// Chey, 2026-08-07: "We'll want to mark when masks are generated by an AI as
// well, because once i've made a few hand-done masks, i want an AI to be able
// to learn from mine to be able to do its best at replicating it across other
// cards in similar sets/series - and then i want to be able to correct the
// agents' mask such that it can then observe the diff and continue to improve
// without me having to hand-paint all the masks."
//
// So provenance here is not a label — it is the record that makes that loop
// mechanical:
//
//   1. WHAT MADE ME        derivation_method + prior.source (+ prior.generator)
//   2. FROM WHAT           prior.generator.exemplars (the human masks it learned
//                          from) / correction.parent (the mask a human edited)
//   3. WHAT THE HUMAN      correction.{parentPng, parentDiffPng, metrics, grid}
//      CHANGED AFTERWARDS  — the training signal, kept as pixels AND numbers
//
// THE LABEL IS NEVER TRUSTED FROM THE CLIENT. `deriveMethod()` decides it by
// diffing the saved pixels against the pixels the claimed starting point
// actually produces. A caller can only *claim* a machine label by supplying a
// full generator identity (name/version/runId/exemplars) — see writeMaskRecord.
//
// v4 (4b, 2026-09-01) adds one field, `frame`, and it obeys the same rule as
// the label: DERIVED, NEVER CLAIMED. Masks now live in CANONICAL SPACE — the
// physical card, 63 x 88 mm at 8 px/mm = 504 x 704 — instead of the 490 x 674
// raster that was 2x TCGdex's 245:337 and 1.55% short of a real card. A mask is
// a stencil, and a stencil only fits if the picture underneath is the shape it
// was cut for, so the stencil is cut to the CARD and every image source
// declares its own transform into that space (data/frames.json). `frame` is
// re-inferred on every read — and inferred from THE MASK PNG'S OWN HEADER
// wherever the file is in reach, not from the width/height the JSON declares,
// because a number in the JSON is a claim and the pixels are not. A
// hand-edited sidecar cannot claim a framing its own pixels deny.
// v1/v2/v3 compatibility is permanent.
//
// See docs/MASK-PIPELINE.md § "Sidecar v3" for the schema.

import { createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { open, readFile, writeFile, unlink, rm, readdir } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import {
  decodePng,
  encodePng,
  diffMask,
  rasterizePriorAlpha,
  renderPriorPng,
  type DiffStats,
  type MaskPrior,
} from './mask-artifacts.ts';
import type { RgbaImage } from './png.ts';
import { headerDims, HEADER_BYTES } from './image-dims.ts';
import { assertAuthorable, resolveFrame, UNKNOWN_FRAME_ID } from './frames.ts';

export const SIDECAR_VERSION = 4;

/** alpha >= 128 counts as foil (same threshold as diffMask). */
const FOIL_THRESHOLD = 128;

// ── The taxonomy ───────────────────────────────────────────────────────────
//
// Five values, covering the four cases that must stay distinguishable:
// pure machine geometry / pure human / human-corrected-machine / machine-unreviewed.

export type DerivationMethod =
  /** Machine geometry only: a window/era rect baked to pixels, not a stroke painted on it. */
  | 'layout-flatten'
  /** Human-painted from scratch or straight from a layout/window prior. */
  | 'hand'
  /** Human-painted ON TOP of an existing NON-AI mask (a bake, or an earlier hand mask). */
  | 'hand-refined'
  /** Machine-generated by a mask generator, NOT yet looked at by a human. */
  | 'ai'
  /** An AI-derived mask a human then edited — the correction record is the product. */
  | 'ai-corrected';

export const DERIVATION_METHODS: readonly DerivationMethod[] = [
  'layout-flatten',
  'hand',
  'hand-refined',
  'ai',
  'ai-corrected',
];

/** Who actually put the pixels there. */
export type Authorship = 'human' | 'machine' | 'mixed';

/** Has a human looked at this mask? Drives the "unreviewed" badge + the queue. */
export type ReviewStatus =
  /** A human painted these pixels. */
  | 'human-authored'
  /** A human chose the geometry (window handles) but painted nothing. */
  | 'human-adjusted'
  /** Machine output no human has touched. NEVER an exemplar. */
  | 'unreviewed';

export const AUTHORSHIP_BY_METHOD: Record<DerivationMethod, Authorship> = {
  'layout-flatten': 'machine',
  hand: 'human',
  'hand-refined': 'human',
  ai: 'machine',
  'ai-corrected': 'mixed',
};

export const REVIEW_BY_METHOD: Record<DerivationMethod, ReviewStatus> = {
  'layout-flatten': 'human-adjusted',
  hand: 'human-authored',
  'hand-refined': 'human-authored',
  ai: 'unreviewed',
  'ai-corrected': 'human-authored',
};

/**
 * ANTI-FEEDBACK-COLLAPSE (the safeguard, enforced in code — not a convention).
 *
 * A generator that learns from its own unreviewed output converges on its own
 * mistakes. So exemplar eligibility is a property of WHO PAINTED THE PIXELS:
 *
 *   - `hand` / `hand-refined` — a human painted them. Ground truth, weight 1.
 *   - `ai-corrected`          — a human painted ON an AI mask. Real signal, but
 *                               anchored by what the AI proposed, so it is
 *                               deliberately worth LESS than an unanchored
 *                               human mask (weight 0.6).
 *   - `ai`                    — unreviewed machine output. Weight 0: it can
 *                               never be an exemplar, at any corpus size.
 *   - `layout-flatten`        — a rect the machine rasterized; teaches only the
 *                               rect the generator already knows. Weight 0.
 *
 * `selectExemplars()` is the ONLY sanctioned way to pick training masks; the
 * codify ritual and every generator go through it.
 */
export const EXEMPLAR_WEIGHT: Record<DerivationMethod, number> = {
  'layout-flatten': 0,
  hand: 1,
  'hand-refined': 1,
  ai: 0,
  'ai-corrected': 0.6,
};

export function isExemplarEligible(method: DerivationMethod): boolean {
  return EXEMPLAR_WEIGHT[method] > 0;
}

// ── Generator identity (the "what made me" half of the chain) ───────────────

/** One human mask a generator learned from. */
export interface ExemplarRef {
  cardId: string;
  variantId: number;
  /** The exemplar's own savedAt — pins WHICH version was learned from. */
  savedAt: string | null;
  /** The exemplar's method at selection time (always human-authored — see EXEMPLAR_WEIGHT). */
  method: DerivationMethod;
  /** Weight this exemplar carried in the run. */
  weight: number;
}

/**
 * Who/what generated a machine mask. Recorded verbatim on the mask AND carried
 * forward onto every human correction of it, so a correction can always answer
 * "which generator, which run, which exemplars produced the thing I fixed".
 */
export interface GeneratorIdentity {
  /** Stable generator name, e.g. 'window-artgate'. */
  name: string;
  /** Generator version — bump when its behavior changes meaning. */
  version: number;
  /** Model id when a model was involved; null for classical-CV generators. */
  modelId: string | null;
  /** Unique id for the batch this mask came out of (groups a trial batch). */
  runId: string;
  /** Everything needed to reproduce the run. */
  params: Record<string, number | string | boolean>;
  /** The human masks it learned from. Empty = it learned from nothing (say so). */
  exemplars: ExemplarRef[];
  /** Generator's own confidence in THIS mask, 0..1, or null if it emits none. */
  confidence: number | null;
  generatedAt: string;
}

// ── Correction record (the training signal) ────────────────────────────────

/** Where the human's corrections landed, as a coarse grid of change fractions. */
export interface CorrectionGrid {
  /** Grid is size × size cells, row-major from the TOP-LEFT of the mask. */
  size: number;
  /** Fraction of each cell's pixels the human changed, 0..1, 3 dp. */
  cells: number[];
}

export interface CorrectionRecord {
  /** The mask the human edited. Its pixels are kept at `parentPng`. */
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    /** sha256 of the parent PNG bytes — pins the exact pixels corrected. */
    sha256: string;
    /** Carried forward when the parent was machine-made. */
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the parent mask's pixels. */
  parentPng: string;
  /** Filename of the human-vs-parent diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** Pixels the human ADDED to the parent. */
  addedPx: number;
  /** Pixels the human REMOVED from the parent. */
  removedPx: number;
  /** Foil pixels human and parent agree on. */
  unchangedPx: number;
  /** Jaccard(human, parent) — 1.0 = the parent was already right. */
  agreement: number;
  /** addedPx + removedPx. */
  changedPx: number;
  /** changedPx / (width*height) — how much of the face the human touched. */
  changedFraction: number;
  /** Bounding box of the changed pixels, UV y-up [x,y,w,h]; null when nothing changed. */
  bbox: [number, number, number, number] | null;
  /** Where the corrections concentrate. */
  grid: CorrectionGrid;
}

// ── Supersede record (a machine write that REPLACED a real mask) ───────────
//
// Distinct from `correction` on purpose. `correction` means "a human edited
// what was here" and is training signal. This means "a generator replaced what
// was here, and no human has agreed yet" — the opposite direction. Blurring
// them would feed a generator's own reshaping back as if a human had endorsed
// it, which is exactly what EXEMPLAR_WEIGHT exists to prevent.
//
// The replaced mask survives twice over: `.parent.png` holds its pixels for
// review, and `archiveDir` holds a VERBATIM copy of every artifact it had, so
// `restoreSuperseded()` puts the original back byte-for-byte — sha256-verified.
// A proposal you cannot un-propose is not a proposal.

export interface SupersededRecord {
  parent: {
    cardId: string;
    variantId: number;
    savedAt: string | null;
    method: DerivationMethod;
    sha256: string;
    generator: GeneratorIdentity | null;
  };
  /** Filename (in this mask's dir) of the replaced mask's pixels. */
  parentPng: string;
  /** Filename of the machine-vs-replaced diff: GREEN added, RED removed. */
  parentDiffPng: string;
  /** The generator run that did it — the handle `revert --run-id` uses. */
  runId: string;
  /** Directory (relative to the mask's own dir) of the verbatim archive. */
  archiveDir: string;
  /** basename → sha256 of the archived bytes. Restore verifies every one. */
  archive: Record<string, string>;
  addedPx: number;
  removedPx: number;
  unchangedPx: number;
  agreement: number;
  changedPx: number;
  changedFraction: number;
  bbox: [number, number, number, number] | null;
  grid: CorrectionGrid;
}

// ── The sidecar ────────────────────────────────────────────────────────────

/** Card context, so a generator lane can group by set/series with no DB. */
export interface MaskCardContext {
  setId: string | null;
  seriesSlug: string | null;
  name: string | null;
  number: string | null;
}

/** One compact ancestry entry (pixels are NOT kept beyond the direct parent). */
export interface LineageEntry {
  method: DerivationMethod;
  /**
   * WHEN THE HUMAN SAVED, carried forward verbatim. On a frame-migration entry
   * this is the pre-migration save's timestamp and is deliberately NOT
   * re-stamped — the alias rule picks the newest save per (cardId, scope) and
   * re-stamping would misreport when the work happened. It therefore does NOT
   * date the migration; `migratedAt` does.
   */
  savedAt: string | null;
  source: MaskPrior['source'];
  generator: { name: string; version: number; runId: string } | null;
  /**
   * v4 (4b): set on a FRAME MIGRATION entry — the mask's pixels were resampled
   * from one frame into another. `derivation_method` deliberately does NOT move
   * with it: nobody repainted anything, so a `hand` mask stays `hand`.
   */
  frameMigration?: { from: string; to: string; runId: string };
  /**
   * WHEN THE MIGRATION RAN. Present exactly on entries that carry
   * `frameMigration`, and it exists because `savedAt` above answers a
   * different question: without it the only entry in the file describing the
   * 4b cutover was stamped with a date in August, which reads as "this
   * migration happened when the human last painted". Two events, two fields.
   */
  migratedAt?: string;
}

const MAX_LINEAGE = 8;

export interface MaskSidecar {
  version: number;
  cardId: string;
  variantId: number;
  artworkKey: string;
  width: number;
  height: number;
  /**
   * v4 (4b): the image frame these pixels live in — an id from
   * `data/frames.json`. `canonical` is 504 x 704, the physical card at
   * 8 px/mm; `tcgdex-high` is the pre-4b 490 x 674 authoring raster.
   *
   * INFERRED, NEVER TRUSTED. normalizeSidecar recomputes it on every read,
   * even when the field is already present, so a hand-edited sidecar cannot
   * claim a frame its pixels deny. The raster is the tell — and where the mask
   * PNG is on disk the raster is read from ITS header rather than from the
   * `width`/`height` beside this field, since those are claims too.
   */
  frame: string;
  channel: string;
  /** THE honest label — derived server-side from pixels, never taken on trust. */
  derivation_method: DerivationMethod;
  /** Rollup of derivation_method (recomputed on read; a stale file cannot lie). */
  authorship: Authorship;
  reviewStatus: ReviewStatus;
  savedAt: string;
  /** URL of the scan the mask was drawn on — what a generator must consume. */
  artworkUrl: string | null;
  card?: MaskCardContext;
  prior: MaskPrior;
  priorPng?: string;
  diffPng?: string;
  /** RULE-vs-mask (v2 semantics, preserved): how wrong the era rule was. */
  diff?: DiffStats;
  /** HUMAN-vs-parent: what the human changed. Present only on a correction. */
  correction?: CorrectionRecord;
  /** MACHINE-vs-replaced: what a generator overwrote, and how to undo it. */
  supersedes?: SupersededRecord;
  /** Oldest → newest ancestry, this save last. Capped at MAX_LINEAGE. */
  lineage?: LineageEntry[];
}

/**
 * Historical alias. The in-memory shape is version-agnostic on purpose — v1
 * through v4 all normalize to it — so the name carries no version from v4 on.
 * @deprecated use `MaskSidecar`.
 */
export type MaskSidecarV3 = MaskSidecar;

// ── Migration: v1/v2/v3 → v4, on read, without touching disk ───────────────

function asMethod(raw: unknown): DerivationMethod | null {
  return typeof raw === 'string' && (DERIVATION_METHODS as readonly string[]).includes(raw)
    ? (raw as DerivationMethod)
    : null;
}

/**
 * The frame a mask's pixels live in, decided by the PIXELS.
 *
 * The raster is the tell, and it is the only tell that cannot be forged by
 * editing a JSON file: a 490 x 674 record was painted in the pre-4b
 * `tcgdex-high` authoring raster, a 504 x 704 record is canonical, and
 * anything else resolves to `unknown`. Resolution goes through the registry
 * (`data/frames.json`) rather than a literal here, so adding a frame is a data
 * change.
 *
 * Same discipline as `derivation_method`: state the system measured, never
 * state a caller claimed. A sidecar hand-edited to say `canonical` over
 * 490 x 674 pixels gets `tcgdex-high` back.
 */
export function inferFrame(width: number, height: number): string {
  return resolveFrame({ width, height }).frameId;
}

/**
 * The raster a caller can PROVE, because it read it out of the image header.
 * See normalizeSidecar: when this is supplied it beats the JSON's own numbers.
 */
export interface PixelDims {
  width: number;
  height: number;
}

/**
 * Normalize ANY sidecar generation to the current in-memory shape.
 *
 * v1 (no prior) and v2 both carried the hardcoded placeholder
 * `derivation_method: 'hand'`. That placeholder is only TRUE for masks that
 * predate this module — every one of them was drawn by Chey with a Pencil,
 * which is exactly what 'hand' means. So legacy files migrate to 'hand' and
 * that is honest, not a guess. From v3 on the label is computed from pixels.
 *
 * v3 → v4 (4b) adds `frame`. A v3 record has no such field and gets the right
 * one anyway, because the field is INFERRED from width/height rather than read
 * — see inferFrame. v1/v2/v3 compatibility is permanent.
 *
 * Derived fields (authorship / reviewStatus / frame) are ALWAYS recomputed
 * here, so a hand-edited or stale sidecar can never claim a status, or a
 * framing, that its own contents deny.
 *
 * `pixels` CLOSES THE LAST HOLE IN THAT RULE. Without it, `frame` is inferred
 * from `width`/`height` — which are JSON, i.e. numbers a caller wrote. The
 * doc-comment claim is that "the raster is the tell, and it is the only tell
 * that cannot be forged by editing a JSON file", and that is only true if the
 * raster comes from the PIXELS. So every caller that has the mask PNG in reach
 * reads its header (foil/image-dims.ts, 32 bytes) and passes the result here;
 * it then wins over the JSON for `width`, `height` AND `frame`, because a
 * sidecar that disagrees with its own PNG is wrong about all three.
 *
 * THE PIXEL-LESS CONTEXTS, where the JSON dims remain the fallback and that is
 * the honest answer rather than a shortcut:
 *
 *   1. A sidecar that arrives as a PARSED OBJECT with no file beside it — an
 *      API response being re-normalized, a record pulled out of a manifest, a
 *      unit-test fixture. There is nothing to read.
 *   2. A HALF-RECORD: the `.json` is on disk but the `.png` is missing or
 *      unreadable. The write paths refuse to create one and both migration
 *      paths throw on it, but a corpus can be damaged out of band, and reading
 *      a damaged record must still tell you what it CLAIMS so you can see the
 *      damage.
 *   3. A file in a format `headerDims` does not parse. It returns null rather
 *      than guessing, and a guess from unreadable bytes would be worse than
 *      the claim already in hand.
 *
 * In every one of those the returned `frame` is inferred from a CLAIM, not a
 * measurement — which is exactly why the on-disk reader below always supplies
 * the pixels.
 */
export function normalizeSidecar(raw: unknown, pixels?: PixelDims | null): MaskSidecar | null {
  if (typeof raw !== 'object' || raw === null) return null;
  const s = raw as Record<string, unknown>;
  if (typeof s.cardId !== 'string' || typeof s.width !== 'number' || typeof s.height !== 'number') return null;

  const width = pixels?.width ?? s.width;
  const height = pixels?.height ?? s.height;
  const method = asMethod(s.derivation_method) ?? 'hand';
  const out: MaskSidecar = {
    ...(s as unknown as MaskSidecar),
    version: typeof s.version === 'number' ? s.version : 1,
    width,
    height,
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    frame: inferFrame(width, height),
    artworkKey: typeof s.artworkKey === 'string' ? s.artworkKey : s.cardId,
    artworkUrl: typeof s.artworkUrl === 'string' ? s.artworkUrl : null,
  };
  return out;
}

/**
 * The mask PNG's OWN raster, from its header. Null when the file is missing or
 * is not a format `headerDims` reads — see normalizeSidecar's pixel-less cases.
 */
export async function readMaskPixelDims(masksDir: string, cardId: string, variantId: string | number): Promise<PixelDims | null> {
  const path = maskPathsIn(masksDir, cardId, variantId).png;
  const fh = await open(path, 'r').catch(() => null);
  if (!fh) return null;
  try {
    const buf = Buffer.alloc(HEADER_BYTES);
    const { bytesRead } = await fh.read(buf, 0, HEADER_BYTES, 0);
    return headerDims(buf.subarray(0, bytesRead));
  } catch {
    return null;
  } finally {
    await fh.close().catch(() => undefined);
  }
}

/** True when the pixels sit in a framing no record covers. */
export function isUnknownFrame(frame: string): boolean {
  return frame === UNKNOWN_FRAME_ID;
}

// ── Method derivation: the label the PIXELS support ────────────────────────

export interface StartingPoint {
  /** What the editor seeded the canvas with. */
  kind: 'layout' | 'window-bake' | 'mask';
  /** The parent mask, when kind === 'mask'. */
  parent?: { cardId: string; variantId: number; sidecar: MaskSidecar | null; png: Buffer };
}

/**
 * Decide the honest method. `painted` is measured, not claimed: the saved
 * alpha is compared to the alpha the starting point actually rasterizes to.
 */
export function deriveMethod(startedFrom: StartingPoint['kind'], parentMethod: DerivationMethod | null, painted: boolean): DerivationMethod {
  if (!painted) {
    // Nothing changed since the seed. If the seed was a mask, this save is a
    // no-op re-save — keep the parent's honest label rather than inventing one.
    return parentMethod ?? 'layout-flatten';
  }
  if (parentMethod === 'ai' || parentMethod === 'ai-corrected') return 'ai-corrected';
  if (parentMethod !== null) return 'hand-refined';
  // Seeded from geometry (era rect or an adjusted window) and painted on:
  // that is a human mask, however it started.
  void startedFrom;
  return 'hand';
}

// ── Pixel helpers ──────────────────────────────────────────────────────────

export function alphaOf(img: RgbaImage): Uint8Array {
  const a = new Uint8Array(img.width * img.height);
  for (let i = 0; i < a.length; i++) a[i] = img.rgba[i * 4 + 3]!;
  return a;
}

export function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

/**
 * BILINEAR resample of an RGBA image — the frame migration's only pixel
 * operation.
 *
 * Bilinear and not the nearest-neighbour sampler the generators use, because a
 * mask is a SOFT-EDGED zone map: the shader reads it through `uMaskFeather`
 * 0.008 UV of blur, and every boundary carries a real antialiasing ramp that
 * `countPaintedOver`'s seam tolerance and `deriveMethod` both depend on.
 * Nearest neighbour would quantise that ramp into a staircase and turn a
 * resample into an edit. Canonical space is larger than the 490 x 674
 * authoring raster in BOTH axes, so this only ever interpolates up.
 *
 * All four channels go through it. Only alpha is the mask; RGB is the display
 * tint, which is a flat colour in every mask the editor writes, so bilinear on
 * it is a no-op in practice and correct if it ever is not.
 */
export function resampleRgba(src: RgbaImage, dw: number, dh: number): RgbaImage {
  const { width: sw, height: sh, rgba: s } = src;
  if (sw === dw && sh === dh) return { width: dw, height: dh, rgba: Uint8Array.from(s) };
  const out = new Uint8Array(dw * dh * 4);
  // Map destination pixel CENTRES back to source pixel centres, so the two
  // rasters describe the same continuous card rather than the same corner.
  const fx = sw / dw;
  const fy = sh / dh;
  for (let y = 0; y < dh; y++) {
    const sy = (y + 0.5) * fy - 0.5;
    const y0 = Math.max(0, Math.min(sh - 1, Math.floor(sy)));
    const y1 = Math.max(0, Math.min(sh - 1, y0 + 1));
    const wy = Math.max(0, Math.min(1, sy - y0));
    for (let x = 0; x < dw; x++) {
      const sx = (x + 0.5) * fx - 0.5;
      const x0 = Math.max(0, Math.min(sw - 1, Math.floor(sx)));
      const x1 = Math.max(0, Math.min(sw - 1, x0 + 1));
      const wx = Math.max(0, Math.min(1, sx - x0));
      const i00 = (y0 * sw + x0) * 4;
      const i01 = (y0 * sw + x1) * 4;
      const i10 = (y1 * sw + x0) * 4;
      const i11 = (y1 * sw + x1) * 4;
      const o = (y * dw + x) * 4;
      for (let c = 0; c < 4; c++) {
        const top = s[i00 + c]! * (1 - wx) + s[i01 + c]! * wx;
        const bot = s[i10 + c]! * (1 - wx) + s[i11 + c]! * wx;
        out[o + c] = Math.round(top * (1 - wy) + bot * wy);
      }
    }
  }
  return { width: dw, height: dh, rgba: out };
}

/**
 * Human-vs-parent correction metrics + a spatial grid. Uses the same
 * foil threshold and diff PNG colors as the rule diff, so the two artifacts
 * are read the same way (GREEN = added, RED = removed).
 */
export function correctionMetrics(
  saved: RgbaImage,
  parentAlpha: Uint8Array,
  gridSize = 4,
): { png: Buffer; stats: DiffStats; changedPx: number; changedFraction: number; bbox: [number, number, number, number] | null; grid: CorrectionGrid } {
  const { width, height } = saved;
  const { png, stats } = diffMask(saved, parentAlpha);
  const cells = new Array<number>(gridSize * gridSize).fill(0);
  const cellCounts = new Array<number>(gridSize * gridSize).fill(0);
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;
  let changedPx = 0;
  for (let y = 0; y < height; y++) {
    const gy = Math.min(gridSize - 1, Math.floor((y / height) * gridSize));
    for (let x = 0; x < width; x++) {
      const i = y * width + x;
      const gx = Math.min(gridSize - 1, Math.floor((x / width) * gridSize));
      const cell = gy * gridSize + gx;
      cellCounts[cell]!++;
      const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
      const inParent = parentAlpha[i]! >= FOIL_THRESHOLD;
      if (inSaved === inParent) continue;
      changedPx++;
      cells[cell]!++;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  const total = width * height;
  // UV y-up bbox — same space as prior.rect, so a generator can use it directly.
  const bbox: [number, number, number, number] | null =
    maxX < 0
      ? null
      : [
          Number((minX / width).toFixed(4)),
          Number((1 - (maxY + 1) / height).toFixed(4)),
          Number(((maxX - minX + 1) / width).toFixed(4)),
          Number(((maxY - minY + 1) / height).toFixed(4)),
        ];
  return {
    png,
    stats,
    changedPx,
    changedFraction: Number((changedPx / total).toFixed(6)),
    bbox,
    grid: {
      size: gridSize,
      cells: cells.map((c, i) => Number((c / (cellCounts[i] || 1)).toFixed(3))),
    },
  };
}

/**
 * Count pixels the human actually painted, relative to a starting alpha plane.
 *
 * `seamTolerant` matters when the start is a RASTERIZED RECT rather than a
 * stored mask. The editor bakes the window with canvas `roundRect` + `fill`;
 * this module rasterizes the same rect from a signed-distance field. Both are
 * correct, and both put ~0.5 coverage on the true edge — so they legitimately
 * disagree in the one-pixel antialiasing band. Measured on the WOTC window at
 * 490×674: 389 of 330,260 px cross the foil threshold differently, and ALL 389
 * sit in that band. Counting them would stamp every unpainted Flatten as
 * `hand`, which is exactly the lie sidecar v3 exists to stop.
 *
 * So a pixel counts as painted only where the SEED IS UNAMBIGUOUS — its 3×3
 * neighbourhood is entirely foil or entirely empty. A brush stroke (>= 4 px)
 * always clears that bar; a rasterizer seam never does. The residual blind
 * spot is a human painting a 1-px line exactly along the window edge, which is
 * both implausible and harmless (the next real stroke reclassifies the save).
 */
export function countPaintedOver(
  saved: RgbaImage,
  seed: Uint8Array,
  width: number,
  height: number,
  seamTolerant: boolean,
): number {
  let n = 0;
  for (let i = 0; i < seed.length; i++) {
    const inSaved = saved.rgba[i * 4 + 3]! >= FOIL_THRESHOLD;
    const inSeed = seed[i]! >= FOIL_THRESHOLD;
    if (inSaved === inSeed) continue;
    if (!seamTolerant) {
      n++;
      continue;
    }
    const x = i % width;
    const y = (i / width) | 0;
    let hi = 0;
    let lo = 0;
    for (let dy = -1; dy <= 1; dy++) {
      const ny = y + dy;
      if (ny < 0 || ny >= height) continue;
      for (let dx = -1; dx <= 1; dx++) {
        const nx = x + dx;
        if (nx < 0 || nx >= width) continue;
        if (seed[ny * width + nx]! >= FOIL_THRESHOLD) hi++;
        else lo++;
      }
    }
    if (hi === 0 || lo === 0) n++; // seed unambiguous here ⇒ a real edit
  }
  return n;
}

// ── Paths ──────────────────────────────────────────────────────────────────

export interface MaskPaths {
  dir: string;
  png: string;
  json: string;
  prior: string;
  diff: string;
  parent: string;
  parentDiff: string;
}

export function maskPathsIn(masksDir: string, cardId: string, variantId: string | number): MaskPaths {
  const dir = join(masksDir, cardId);
  return {
    dir,
    png: join(dir, `${variantId}.png`),
    json: join(dir, `${variantId}.json`),
    prior: join(dir, `${variantId}.prior.png`),
    diff: join(dir, `${variantId}.diff.png`),
    parent: join(dir, `${variantId}.parent.png`),
    parentDiff: join(dir, `${variantId}.parent.diff.png`),
  };
}

/**
 * Read a sidecar off disk, resolved against ITS OWN PIXELS.
 *
 * The mask PNG is right there, so this is the context where "the raster is the
 * tell" can actually be honoured: the header is read (32 bytes) and beats
 * whatever the JSON says about its own dimensions. A `.json` whose `width` was
 * hand-edited, or written stale by a client, reads back with the frame the
 * pixels support. A missing/unreadable PNG falls back to the JSON — see
 * normalizeSidecar case 2.
 */
export async function readSidecarFile(
  masksDir: string,
  cardId: string,
  variantId: string | number,
): Promise<MaskSidecar | null> {
  const text = await readFile(maskPathsIn(masksDir, cardId, variantId).json, 'utf8').catch(() => null);
  if (text === null) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(text) as unknown;
  } catch {
    return null;
  }
  return normalizeSidecar(parsed, await readMaskPixelDims(masksDir, cardId, variantId));
}

/** Where a generator run parks the mask it replaced. Committed with the corpus. */
export function archiveDirName(variantId: string | number, runId: string): string {
  return join('superseded', `${variantId}.${runId.replace(/[^A-Za-z0-9._-]/g, '_')}`);
}

/**
 * The archive is SELF-DESCRIBING on disk (`archive.json`), not merely pointed
 * at by the sidecar. That matters: once Chey corrects a generated mask the live
 * sidecar stops being about the supersede, but his original must still be one
 * command away. So the undo reads the manifest from the archive itself.
 */
export interface ArchiveManifest {
  version: 1;
  cardId: string;
  variantId: number;
  runId: string;
  archivedAt: string;
  /** The replaced mask's method — what a restore puts back. */
  method: DerivationMethod;
  /** basename → sha256 of the archived bytes. */
  files: Record<string, string>;
}

const ARCHIVE_MANIFEST = 'archive.json';

/**
 * Copy every artifact currently on disk into the run's archive, VERBATIM, and
 * drop a manifest beside them. Returns basename → sha256 so a restore can
 * prove it put back the same BYTES, not a re-serialization that merely looks
 * equivalent.
 */
async function archiveExisting(
  paths: MaskPaths,
  cardId: string,
  variantId: string,
  runId: string,
  method: DerivationMethod,
): Promise<Record<string, string>> {
  const dir = join(paths.dir, archiveDirName(variantId, runId));
  mkdirSync(dir, { recursive: true });
  const files: Record<string, string> = {};
  for (const src of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    const buf = await readFile(src).catch(() => null);
    if (!buf) continue;
    const name = basename(src);
    await writeFile(join(dir, name), buf);
    files[name] = sha256(buf);
  }
  const manifest: ArchiveManifest = {
    version: 1,
    cardId,
    variantId: Number(variantId),
    runId,
    archivedAt: new Date().toISOString(),
    method,
    files,
  };
  await writeFile(join(dir, ARCHIVE_MANIFEST), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return files;
}

export interface FoundArchive {
  cardId: string;
  variantId: number;
  runId: string;
  /** Absolute path of the archive directory. */
  dir: string;
  manifest: ArchiveManifest;
}

/** Every generator archive on disk, optionally filtered to one run. */
export async function findArchives(masksDir: string, runId?: string | null): Promise<FoundArchive[]> {
  const out: FoundArchive[] = [];
  const cardDirs = await readdir(masksDir).catch(() => [] as string[]);
  for (const cardId of cardDirs) {
    if (cardId === 'codified') continue;
    const supDir = join(masksDir, cardId, 'superseded');
    const runs = await readdir(supDir).catch(() => [] as string[]);
    for (const r of runs) {
      const dir = join(supDir, r);
      const raw = await readFile(join(dir, ARCHIVE_MANIFEST), 'utf8').catch(() => null);
      if (!raw) continue;
      const manifest = JSON.parse(raw) as ArchiveManifest;
      if (runId && manifest.runId !== runId) continue;
      out.push({ cardId, variantId: manifest.variantId, runId: manifest.runId, dir, manifest });
    }
  }
  return out.sort((a, b) => (a.cardId === b.cardId ? a.variantId - b.variantId : a.cardId < b.cardId ? -1 : 1));
}

export interface RestoreResult {
  cardId: string;
  variantId: number;
  runId: string;
  /** Files put back, with the sha256 that was verified on each. */
  restored: { file: string; sha256: string }[];
  /** The method the restored mask carries — i.e. what Chey gets back. */
  method: DerivationMethod;
}

/**
 * Put back exactly what a generator run replaced. Byte-for-byte: every file is
 * read from the archive and re-hashed against the manifest recorded at
 * supersede time, and the WHOLE archive is verified before a single live file
 * is deleted — so a corrupt archive can never turn "undo" into "lose both".
 */
export async function restoreArchive(masksDir: string, found: FoundArchive): Promise<RestoreResult> {
  const paths = maskPathsIn(masksDir, found.cardId, found.variantId);
  const staged: { name: string; buf: Buffer; sha: string }[] = [];
  for (const [name, sha] of Object.entries(found.manifest.files)) {
    const buf = await readFile(join(found.dir, name));
    const got = sha256(buf);
    if (got !== sha) throw new Error(`archive ${found.dir}/${name} is corrupt (sha256 ${got} != ${sha})`);
    staged.push({ name, buf, sha });
  }
  if (!staged.some((s) => s.name === `${found.variantId}.png`)) {
    throw new Error(`archive ${found.dir} has no ${found.variantId}.png — refusing to delete the live mask`);
  }

  for (const f of [paths.png, paths.json, paths.prior, paths.diff, paths.parent, paths.parentDiff]) {
    await unlink(f).catch(() => undefined);
  }
  for (const s of staged) await writeFile(join(paths.dir, s.name), s.buf);
  await rm(found.dir, { recursive: true, force: true });
  const left = await readdir(join(paths.dir, 'superseded')).catch(() => null);
  if (left && left.length === 0) await rm(join(paths.dir, 'superseded'), { recursive: true, force: true });

  const back = await readSidecarFile(masksDir, found.cardId, found.variantId);
  return {
    cardId: found.cardId,
    variantId: found.variantId,
    runId: found.runId,
    restored: staged.map((s) => ({ file: s.name, sha256: s.sha })),
    method: back?.derivation_method ?? found.manifest.method,
  };
}

// ── Frame migration (4b): the corpus moves rasters, nobody repaints ────────
//
// A THIRD kind of write, deliberately distinct from both `correction` (a human
// edited this) and `supersedes` (a generator replaced this). Neither describes
// what happens here: the mask is resampled from one frame into another and the
// SHAPE IT ENCODES IS UNCHANGED. So `derivation_method` does not move — a
// `hand` mask stays `hand`, because nobody repainted anything — and neither
// does `savedAt`, because the alias rule picks the newest save per
// (cardId, scope) and re-stamping it would misreport when the human worked.
//
// It reuses `archiveExisting` rather than growing a second archival route: the
// pre-migration bytes go into `superseded/<variantId>.<runId>/` verbatim with a
// sha256 per file, BEFORE anything is replaced, and `restoreArchive` undoes the
// whole pass with `revert --run-id`.

export interface FrameMigrationInput {
  masksDir: string;
  cardId: string;
  variantId: string | number;
  /** Frame id the pixels are moving INTO (an id in data/frames.json). */
  toFrame: string;
  /** Target raster — must be the target frame's raster. */
  width: number;
  height: number;
  /** Groups the whole pass. The handle `revert --run-id` uses. */
  runId: string;
}

export interface FrameMigrationResult {
  cardId: string;
  variantId: number;
  from: { frame: string; width: number; height: number };
  to: { frame: string; width: number; height: number };
  /** basename → sha256 of the pre-migration bytes, verified into the archive. */
  archive: Record<string, string>;
  archiveDir: string;
  /** Unchanged by construction — asserted, not assumed. */
  method: DerivationMethod;
  sidecar: MaskSidecar;
  /** Correction metrics before and after, when this mask carries a correction. */
  correctionDrift: { before: number; after: number } | null;
}

export async function migrateMaskFrame(input: FrameMigrationInput): Promise<FrameMigrationResult> {
  const { masksDir, cardId, runId, toFrame, width, height } = input;
  const variantId = String(input.variantId);
  const paths = maskPathsIn(masksDir, cardId, variantId);

  const existing = await readSidecarFile(masksDir, cardId, variantId);
  if (!existing) throw new Error(`${cardId}/${variantId} has no readable sidecar`);
  const livePng = await readFile(paths.png).catch(() => null);
  if (!livePng) throw new Error(`${cardId}/${variantId} has a sidecar but no mask PNG — refusing to migrate a half-record`);

  if (existing.supersedes) {
    // No live sidecar carries one today. Carrying the block forward unchanged
    // would leave its recorded parent sha256 pointing at a file this pass is
    // about to resample, i.e. a provenance record that no longer verifies.
    // Refuse loudly rather than emit that.
    throw new Error(
      `${cardId}/${variantId} carries a \`supersedes\` block; frame migration of a superseded record is not ` +
        'implemented, because resampling its .parent.png would falsify supersedes.parent.sha256. Restore or ' +
        'accept the supersede first (revert --run-id), then migrate.',
    );
  }

  const saved = decodePng(livePng);
  if (saved.width === width && saved.height === height && existing.frame === toFrame) {
    return {
      cardId,
      variantId: Number(variantId),
      from: { frame: existing.frame, width: saved.width, height: saved.height },
      to: { frame: toFrame, width, height },
      archive: {},
      archiveDir: '',
      method: existing.derivation_method,
      sidecar: existing,
      correctionDrift: null,
    };
  }

  // 1. ARCHIVE FIRST, while the originals are still on disk. Same route the
  //    supersede path uses, so there is one archival code path, not two.
  const archive = await archiveExisting(paths, cardId, variantId, runId, existing.derivation_method);

  // 2. The mask itself.
  const migrated = resampleRgba(saved, width, height);
  const migratedPng = encodePng(migrated);

  // 3. The rule artifacts. The prior is FRACTIONAL — rects are fractions of the
  //    card face, invariant under the resample — so it is re-rasterized at the
  //    new raster rather than resampled. Regenerating is exact; resampling a
  //    rasterization is a copy of a copy.
  const priorPng = renderPriorPng(width, height, existing.prior);
  const ruleAlpha = rasterizePriorAlpha(width, height, existing.prior);
  const { png: diffPng, stats } = diffMask(migrated, ruleAlpha);

  // 4. The correction, when there is one. Both sides are now canonical, so the
  //    metrics are RECOMPUTED — they have to describe the pixels actually on
  //    disk. The drift is reported rather than hidden: the human's edit is the
  //    same edit, measured on a finer grid.
  let correction: CorrectionRecord | undefined;
  let correctionDrift: FrameMigrationResult['correctionDrift'] = null;
  if (existing.correction) {
    const parentBuf = await readFile(paths.parent).catch(() => null);
    if (!parentBuf) {
      throw new Error(`${cardId}/${variantId} claims a correction but ${basename(paths.parent)} is missing`);
    }
    const parentMigrated = resampleRgba(decodePng(parentBuf), width, height);
    const parentPngBytes = encodePng(parentMigrated);
    const m = correctionMetrics(migrated, alphaOf(parentMigrated));
    correction = {
      ...existing.correction,
      parent: { ...existing.correction.parent, sha256: sha256(parentPngBytes) },
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    correctionDrift = { before: existing.correction.agreement, after: m.stats.agreement };
    await writeFile(paths.parent, parentPngBytes);
    await writeFile(paths.parentDiff, m.png);
  }

  // 5. The lineage entry. It says what this was — a frame migration — and it
  //    carries the method FORWARD rather than inventing one.
  const lineage: LineageEntry[] = [
    ...(existing.lineage ?? [
      {
        method: existing.derivation_method,
        savedAt: existing.savedAt ?? null,
        source: existing.prior?.source ?? 'layout',
        generator: existing.prior?.generator
          ? {
              name: existing.prior.generator.name,
              version: existing.prior.generator.version,
              runId: existing.prior.generator.runId,
            }
          : null,
      },
    ]),
    {
      method: existing.derivation_method,
      // The HUMAN's save date, carried forward unchanged — see LineageEntry.
      savedAt: existing.savedAt ?? null,
      source: existing.prior?.source ?? 'layout',
      generator: null,
      frameMigration: { from: existing.frame, to: toFrame, runId },
      // …and the date of THIS event, which is a different one.
      migratedAt: new Date().toISOString(),
    },
  ].slice(-MAX_LINEAGE);

  const sidecar: MaskSidecar = {
    ...existing,
    version: SIDECAR_VERSION,
    width,
    height,
    frame: toFrame,
    // Unchanged on purpose. Nobody repainted anything, and the alias rule picks
    // the newest save per (cardId, scope).
    derivation_method: existing.derivation_method,
    authorship: AUTHORSHIP_BY_METHOD[existing.derivation_method],
    reviewStatus: REVIEW_BY_METHOD[existing.derivation_method],
    savedAt: existing.savedAt,
    diff: stats,
    ...(correction ? { correction } : {}),
    lineage,
  };

  mkdirSync(paths.dir, { recursive: true });
  await writeFile(paths.png, migratedPng);
  await writeFile(paths.prior, priorPng);
  await writeFile(paths.diff, diffPng);
  await writeFile(paths.json, JSON.stringify(sidecar, null, 2) + '\n', 'utf8');

  if (sidecar.derivation_method !== existing.derivation_method) {
    throw new Error('invariant violated: a frame migration changed derivation_method');
  }

  return {
    cardId,
    variantId: Number(variantId),
    from: { frame: existing.frame, width: saved.width, height: saved.height },
    to: { frame: toFrame, width, height },
    archive,
    archiveDir: archiveDirName(variantId, runId),
    method: existing.derivation_method,
    sidecar,
    correctionDrift,
  };
}

// ── THE single write path ──────────────────────────────────────────────────

export interface WriteMaskInput {
  masksDir: string;
  cardId: string;
  variantId: string;
  /** The mask PNG bytes (alpha = coverage). */
  png: Buffer;
  width: number;
  height: number;
  /** The deterministic era-rule prior (always recorded — keeps the codify score alive). */
  prior: MaskPrior;
  /** What the canvas was seeded with. Only affects which pixels `painted` is measured against. */
  startedFrom: StartingPoint['kind'];
  /** Claimed parent (cardId/variantId) when startedFrom === 'mask'. */
  parentRef?: { cardId: string; variantId: number } | null;
  artworkUrl?: string | null;
  card?: MaskCardContext;
  /**
   * ONLY a real generator may claim a machine label, and only by handing over
   * a full identity. No identity ⇒ the method is derived from pixels.
   */
  machine?: GeneratorIdentity | null;
  /**
   * Machine writes only: explicit consent to land on top of a mask that is
   * already there — including a HUMAN one. Without it, a generator write over
   * anything but its own unreviewed output THROWS. With it, every artifact the
   * mask had is archived verbatim under `superseded/<variantId>.<runId>/`,
   * `.parent.png` keeps the replaced pixels, and `supersedes` records the
   * sha256s that make `restoreSuperseded()` an exact undo.
   */
  supersede?: { runId: string } | null;
}

/**
 * Write a mask + every provenance artifact, stamping the method the pixels
 * support. Used by the foil-lab PUT route AND by generators — one path, so
 * "every write path stamps honestly" is structural, not a promise.
 */
export async function writeMaskRecord(input: WriteMaskInput): Promise<MaskSidecar> {
  const { masksDir, cardId, variantId, png, width, height, prior } = input;
  const paths = maskPathsIn(masksDir, cardId, variantId);
  const saved = decodePng(png);
  if (saved.width !== width || saved.height !== height) throw new Error('png dimensions do not match width/height');

  // ── THE FRAME GATE (4b) ──
  //
  // Derived from the pixels, never claimed. An unregistered raster is not a
  // mask you save carefully — it is a mask you do not save: a stencil cut for
  // a picture nobody can name is worse than no stencil, because nothing
  // downstream can tell it apart from a good one.
  const frameRes = resolveFrame({ width, height, eraId: prior?.eraId ?? null });
  assertAuthorable(frameRes);
  const frame = frameRes.frameId;

  // ── The parent: what this save is replacing / was painted on top of ──
  //
  // SAFETY RULE: whatever the client claims, if the file at the target path is
  // unreviewed machine output ('ai'), it IS the parent. Otherwise a client that
  // forgot to report the parent would silently launder an AI mask into 'hand'
  // and the correction signal — the whole point — would be lost.
  const existing = await readSidecarFile(masksDir, cardId, variantId);
  let parentRef = input.parentRef ?? null;
  if (existing?.derivation_method === 'ai') parentRef = { cardId, variantId: Number(variantId) };

  // A generator landing on an existing mask must say so out loud. Silence used
  // to mean "overwrite", which is how human work disappears.
  const supersede = input.machine ? (input.supersede ?? null) : null;
  if (input.machine && existing && !supersede) {
    throw new Error(
      `${cardId}/${variantId} already has a ${existing.derivation_method} mask. A generator may only replace it with ` +
        'an explicit supersede { runId } — which archives the original byte-for-byte so `revert --run-id` undoes it.',
    );
  }

  let parentSidecar: MaskSidecar | null = null;
  let parentPngBuf: Buffer | null = null;
  if (parentRef) {
    const pp = maskPathsIn(masksDir, parentRef.cardId, parentRef.variantId);
    parentPngBuf = await readFile(pp.png).catch(() => null);
    if (parentPngBuf) parentSidecar = await readSidecarFile(masksDir, parentRef.cardId, parentRef.variantId);
    else parentRef = null; // claimed a parent that isn't on disk — treat as none
  }

  // ── `painted`: measured against the pixels the starting point produces ──
  let startingAlpha: Uint8Array;
  let seamTolerant: boolean;
  if (parentPngBuf) {
    // Both masks came out of the SAME rasterizer (the editor canvas), so an
    // exact comparison is correct — every differing pixel is a human stroke.
    startingAlpha = alphaOf(decodePng(parentPngBuf));
    seamTolerant = false;
  } else {
    // Geometry seed. A window bake starts from the ADJUSTED rect when there is
    // one (that is what MaskEditor/Flatten rasterize); otherwise the era rule.
    const geom: MaskPrior =
      input.startedFrom === 'window-bake' && prior.window
        ? { ...prior, rect: prior.window.rect, radius: prior.window.radius }
        : prior;
    startingAlpha = rasterizePriorAlpha(width, height, geom);
    seamTolerant = true;
  }
  const painted = countPaintedOver(saved, startingAlpha, width, height, seamTolerant) > 0;

  const machine = input.machine ?? null;
  const method: DerivationMethod = machine
    ? 'ai'
    : deriveMethod(input.startedFrom, parentSidecar?.derivation_method ?? (parentPngBuf ? 'hand' : null), painted);

  // ── prior.source + generator carry-forward ──
  const inheritedGenerator =
    machine ??
    parentSidecar?.prior?.generator ??
    (parentSidecar?.correction?.parent.generator ?? null);
  const source: MaskPrior['source'] = machine
    ? 'ai'
    : parentSidecar && (parentSidecar.derivation_method === 'ai' || parentSidecar.derivation_method === 'ai-corrected')
      ? 'ai'
      : parentRef
        ? 'mask'
        : input.startedFrom === 'window-bake' && prior.window
          ? 'window'
          : 'layout';

  const replacedRef =
    parentRef && parentSidecar
      ? { cardId: parentRef.cardId, variantId: parentRef.variantId, sidecar: parentSidecar }
      : supersede && existing
        ? { cardId, variantId: Number(variantId), sidecar: existing }
        : null;

  const fullPrior: MaskPrior = {
    ...prior,
    source,
    ...(inheritedGenerator ? { generator: inheritedGenerator } : {}),
    ...(replacedRef
      ? {
          parentMask: {
            cardId: replacedRef.cardId,
            variantId: replacedRef.variantId,
            savedAt: replacedRef.sidecar.savedAt ?? null,
            method: replacedRef.sidecar.derivation_method,
          },
        }
      : {}),
  };

  // ── Rule-vs-mask artifacts (v2 semantics — the codify score) ──
  const ruleAlpha = rasterizePriorAlpha(width, height, prior);
  const priorPng = renderPriorPng(width, height, prior);
  const { png: diffPng, stats } = diffMask(saved, ruleAlpha);

  // ── Human-vs-parent artifacts (the correction signal) ──
  let correction: CorrectionRecord | undefined;
  if (parentRef && parentPngBuf && painted && !machine) {
    const m = correctionMetrics(saved, alphaOf(decodePng(parentPngBuf)));
    correction = {
      parent: {
        cardId: parentRef.cardId,
        variantId: parentRef.variantId,
        savedAt: parentSidecar?.savedAt ?? null,
        method: parentSidecar?.derivation_method ?? 'hand',
        sha256: sha256(parentPngBuf),
        generator: parentSidecar?.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, parentPngBuf);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Machine-vs-replaced artifacts + the verbatim undo archive ──
  //
  // Order matters: archive FIRST (while the originals are still on disk),
  // then write the parent pixels + change map, then the sidecar. A crash
  // between steps leaves the archive intact, which is the safe direction.
  let supersedes: SupersededRecord | undefined;
  if (supersede && existing) {
    const replacedPng = await readFile(paths.png).catch(() => null);
    if (!replacedPng) {
      throw new Error(`${cardId}/${variantId} has a sidecar but no mask PNG — refusing to supersede a half-record`);
    }
    const archive = await archiveExisting(paths, cardId, variantId, supersede.runId, existing.derivation_method);
    const m = correctionMetrics(saved, alphaOf(decodePng(replacedPng)));
    supersedes = {
      parent: {
        cardId,
        variantId: Number(variantId),
        savedAt: existing.savedAt ?? null,
        method: existing.derivation_method,
        sha256: sha256(replacedPng),
        generator: existing.prior?.generator ?? null,
      },
      parentPng: `${variantId}.parent.png`,
      parentDiffPng: `${variantId}.parent.diff.png`,
      runId: supersede.runId,
      archiveDir: archiveDirName(variantId, supersede.runId),
      archive,
      addedPx: m.stats.addedPx,
      removedPx: m.stats.removedPx,
      unchangedPx: m.stats.unchangedPx,
      agreement: m.stats.agreement,
      changedPx: m.changedPx,
      changedFraction: m.changedFraction,
      bbox: m.bbox,
      grid: m.grid,
    };
    mkdirSync(paths.dir, { recursive: true });
    await writeFile(paths.parent, replacedPng);
    await writeFile(paths.parentDiff, m.png);
  }

  // ── Lineage: the parent's chain (which already ENDS with the parent's own
  // entry — don't append it twice) plus this save. Pre-v3 parents have no
  // lineage array, so synthesize their single entry from what they do record.
  const savedAt = new Date().toISOString();
  const ancestor = parentSidecar ?? (supersede ? existing : null);
  const parentLineage: LineageEntry[] = ancestor
    ? (ancestor.lineage ?? [
        {
          method: ancestor.derivation_method,
          savedAt: ancestor.savedAt ?? null,
          source: ancestor.prior?.source ?? 'layout',
          generator: ancestor.prior?.generator
            ? {
                name: ancestor.prior.generator.name,
                version: ancestor.prior.generator.version,
                runId: ancestor.prior.generator.runId,
              }
            : null,
        },
      ])
    : [];
  const lineage: LineageEntry[] = [
    ...parentLineage,
    {
      method,
      savedAt,
      source,
      generator: machine ? { name: machine.name, version: machine.version, runId: machine.runId } : null,
    },
  ].slice(-MAX_LINEAGE);

  const sidecar: MaskSidecar = {
    version: SIDECAR_VERSION,
    cardId,
    variantId: Number(variantId),
    // Identity rule (unchanged since v2): a mask belongs to the card's SCAN.
    // The FRAME is not part of that identity and never enters an alias key:
    // one mask per (cardId, scope), stored in canonical space, transformed out
    // to whatever image it is drawn over.
    artworkKey: cardId,
    width,
    height,
    frame,
    channel: 'alpha',
    derivation_method: method,
    authorship: AUTHORSHIP_BY_METHOD[method],
    reviewStatus: REVIEW_BY_METHOD[method],
    savedAt,
    artworkUrl: input.artworkUrl ?? existing?.artworkUrl ?? null,
    ...(input.card ? { card: input.card } : existing?.card ? { card: existing.card } : {}),
    prior: fullPrior,
    priorPng: `${variantId}.prior.png`,
    diffPng: `${variantId}.diff.png`,
    diff: stats,
    ...(correction ? { correction } : {}),
    ...(supersedes ? { supersedes } : {}),
    lineage,
  };

  mkdirSync(paths.dir, { recursive: true });
  await writeFile(paths.png, png);
  await writeFile(paths.prior, priorPng);
  await writeFile(paths.diff, diffPng);
  // A save with neither a correction nor a supersede must not leave a STALE
  // parent artifact behind.
  if (!correction && !supersedes) {
    await unlink(paths.parent).catch(() => undefined);
    await unlink(paths.parentDiff).catch(() => undefined);
  }
  await writeFile(paths.json, JSON.stringify(sidecar, null, 2) + '\n', 'utf8');
  return sidecar;
}
