// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Chey Rasmussen
//
// The contribution queue, client side: the artifact's shape and the two pure
// functions that turn it into what the page shows.
//
// Everything here is PURE and separate from the rendering on purpose. "Does
// the skill filter show the right cards" and "does the type filter compose
// with it" are questions about a list, and answering them in a unit test is
// cheaper and more exact than answering them in a browser — the E2E run then
// only has to prove the control is wired to the function, not that the
// function is right.
//
// NOTHING IS COMPUTED HERE. Impact, estimate, skill, guards and the sort order
// are all decided by tools/task-queue/build.ts and baked into the artifact, so
// the page and the CLI can never disagree about what the queue says. This file
// filters and counts; it does not rank.
//
// ── THE ARTIFACT CAN BE NEWER THAN THIS CLIENT ─────────────────────────────
//
// `task-queue.json` is a BUILD OUTPUT fetched at runtime, and the two halves
// can ship apart: a bake regenerated by a newer builder, a cached bundle, an
// SPA rolled back while the data was not. So the unions below are what THIS
// build knows, never what the file may contain — the ids are widened with
// `& {}` (which keeps the literals as autocomplete hints while admitting any
// string), and every label lookup goes through `typeLabel` / `skillLabel` /
// `estimateLabel`, which degrade to the raw slug.
//
// That is not defensive decoration. `TYPE_LABEL[task.type].what` on a type this
// build had never heard of threw during render, React unmounted the tree, and
// the production queue — the editor's LANDING PAGE — went white while every
// test in the repository passed, because the fixture happened to rank the new
// cards off the first screen. A card must render degraded-but-alive instead,
// and a chip must appear for the unknown kind rather than hiding its cards
// behind a control that is not there.

/** The tiers, in the order a contributor scans them. Matches build.ts. */
export type Estimate = 'minutes' | 'half-hour' | 'hours'

export type Skill = 'mask' | 'slider' | 'glsl' | 'research' | 'live-tilt' | 'art'

export type TaskType =
  | 'approximation'
  | 'canon'
  | 'verdict'
  | 'mask'
  | 'window-mask'
  | 'residual'
  | 'empty-pool'
  | 'ink-tile'

/**
 * What the ARTIFACT can actually carry: one of the ids above, or one a newer
 * builder emitted. `& {}` is the idiom that widens the union to `string`
 * without losing the literals as editor hints.
 */
export type SkillId = Skill | (string & {})
export type TaskTypeId = TaskType | (string & {})
export type EstimateId = Estimate | (string & {})

export interface Task {
  id: string
  type: TaskTypeId
  title: string
  need: string
  skill: SkillId
  estimate: EstimateId
  estimateWhy: string
  impact: number | null
  impactWhy: string
  link: string | null
  source: string
  guards: string[]
  tieBreak: number
  detail: Record<string, string | number | boolean | null>
}

export interface EmptyPool {
  patternId: string
  reason: string
  detail: string
  citedPrintings: number
  alternates: number
  outrankedBy: { patternId: string; printings: number }[]
  implies: string
}

export interface Reconciliation {
  key: string
  claim: string
  claimedAt: string
  measured: string
  agrees: boolean
  note: string
}

export interface TaskQueueFile {
  version: number
  generatedAt: string
  source: string | null
  resolverVersion: number | null
  skills: Record<string, string>
  guards: Record<string, string>
  estimateTiers: Record<string, string>
  bakedInputs: Record<string, boolean>
  counts: {
    tasks: number
    byType: Record<string, number>
    bySkill: Record<string, number>
    impactTotal: number
    unsized: number
  }
  reconciliation: Reconciliation[]
  emptyPools: EmptyPool[]
  tasks: Task[]
}

/**
 * The badge each type wears, and the one-line answer to "what IS this".
 *
 * A type badge that only repeated the slug would be decoration. The second
 * string is what a contributor who has never seen this queue needs in order to
 * decide whether the card is for them.
 */
export const TYPE_LABEL: Record<TaskType, { badge: string; what: string }> = {
  mask: {
    badge: 'mask',
    what: 'A machine drew this mask and nobody checked it, so it carries no exemplar weight.',
  },
  'window-mask': {
    badge: 'first mask',
    what: 'A rule with no admissible exemplar anywhere. The first hand mask here seeds a whole group.',
  },
  canon: {
    badge: 'canon',
    what: 'No saved uniform snapshot, so this pattern renders whatever the code defaults happen to be.',
  },
  approximation: {
    badge: 'recipe',
    what: 'No faithful GLSL — this type renders through another recipe and says so.',
  },
  verdict: {
    badge: 'verdict',
    what: 'A judging round returned a nay that nothing has closed.',
  },
  residual: {
    badge: 'residual',
    what: 'The research recorded a claim it could not target down to specific cards.',
  },
  'empty-pool': {
    badge: 'empty pool',
    what: 'An implemented recipe the resolver never picks. The bake says which of four causes.',
  },
  'ink-tile': {
    badge: 'ink tile',
    what: 'A reverse-holo design slot left empty on purpose: the mark is a trademark, so it wants an ORIGINAL recreation rather than a trace.',
  },
}

/** How long, in words a contributor can plan around. */
export const ESTIMATE_LABEL: Record<Estimate, string> = {
  minutes: 'minutes',
  'half-hour': 'about half an hour',
  hours: 'hours',
}

export const SKILL_ORDER: Skill[] = ['mask', 'slider', 'glsl', 'research', 'live-tilt', 'art']

export const SKILL_LABEL: Record<Skill, string> = {
  mask: 'Mask drawing',
  slider: 'Slider tuning',
  glsl: 'GLSL',
  research: 'Research / citation',
  'live-tilt': 'Live tilt',
  art: 'Original geometry',
}

export const TYPE_ORDER: TaskType[] = [
  'mask',
  'window-mask',
  'canon',
  'approximation',
  'verdict',
  'residual',
  'empty-pool',
  'ink-tile',
]

// ── The degrading lookups ──────────────────────────────────────────────────
//
// One rule, three functions: an id this build does not know renders AS ITSELF.
// Never a throw, never a blank, and never a silent drop — a contributor who can
// see "ink tile" on a card can at least read the card, and the page stays up
// for the hundred cards that are not new.

// `Object.hasOwn` rather than `map[id] ?? fallback`, and that is load-bearing
// rather than pedantry: `SKILL_LABEL['toString']` inherits a FUNCTION off the
// prototype, and React throws on a function child — so the plain `??` guard
// would have turned one adversarial slug back into the white screen it was
// written to prevent.

/** The badge and the one-line "what IS this", for a known type or any other. */
export function typeLabel(type: TaskTypeId): { badge: string; what: string } {
  if (Object.hasOwn(TYPE_LABEL, type)) return TYPE_LABEL[type as TaskType]
  return {
    badge: type,
    what:
      'This queue was generated by a newer build than the page you are looking at, which has no description for ' +
      'this kind of task yet. The card is the artifact’s own text, unedited.',
  }
}

/** The skill's human name, or the raw slug when the artifact is ahead of us. */
export function skillLabel(skill: SkillId): string {
  return Object.hasOwn(SKILL_LABEL, skill) ? SKILL_LABEL[skill as Skill] : skill
}

/** The estimate in words, or the raw tier when the artifact is ahead of us. */
export function estimateLabel(estimate: EstimateId): string {
  return Object.hasOwn(ESTIMATE_LABEL, estimate) ? ESTIMATE_LABEL[estimate as Estimate] : estimate
}

/**
 * The chip order for a list of tasks: the ids THIS build knows, in the order a
 * contributor scans them, followed by any id only the artifact knows, in the
 * order it first appears.
 *
 * Appending rather than dropping is the point. A filter row built purely from
 * `TYPE_ORDER` would silently have no chip for a new kind, so its cards could
 * be read but never isolated — a filter that quietly cannot express part of the
 * list it filters.
 */
function orderFor<T extends string>(known: readonly T[], present: readonly string[]): string[] {
  const out: string[] = [...known]
  for (const id of present) if (!out.includes(id)) out.push(id)
  return out
}

export function typeOrderFor(tasks: Task[]): string[] {
  return orderFor(TYPE_ORDER, tasks.map((t) => t.type))
}

export function skillOrderFor(tasks: Task[]): string[] {
  return orderFor(SKILL_ORDER, tasks.map((t) => t.skill))
}

export interface Filters {
  /** null = every skill. */
  skill: SkillId | null
  /** null = every type. */
  type: TaskTypeId | null
}

/**
 * Apply the filters. The artifact is already sorted by impact, so this
 * PRESERVES ORDER rather than re-sorting — a filtered list that re-ranked
 * itself would show a different "most valuable next thing" depending on which
 * chip happened to be pressed, which is the opposite of what a ranking is for.
 */
export function filterTasks(tasks: Task[], f: Filters): Task[] {
  return tasks.filter((t) => (f.skill === null || t.skill === f.skill) && (f.type === null || t.type === f.type))
}

/**
 * How many cards each chip would show, given the OTHER filter.
 *
 * Counted against the co-filter rather than against everything, so a chip that
 * would produce an empty list can be shown as empty before it is pressed. A
 * dead-end control that only reveals itself after a click is worse than one
 * that says so.
 */
export function chipCounts(tasks: Task[], f: Filters): { skills: Record<string, number>; types: Record<string, number> } {
  const skills: Record<string, number> = {}
  const types: Record<string, number> = {}
  for (const t of tasks) {
    if (f.type === null || t.type === f.type) skills[t.skill] = (skills[t.skill] ?? 0) + 1
    if (f.skill === null || t.skill === f.skill) types[t.type] = (types[t.type] ?? 0) + 1
  }
  return { skills, types }
}

/** Printings governed by a list of cards; unsizeable cards contribute nothing. */
export function impactOf(tasks: Task[]): number {
  return tasks.reduce((n, t) => n + (t.impact ?? 0), 0)
}
